mcproxy/Makefile
mcproxy/files/mcproxy.conf
mcproxy/files/mcproxy.config
mcproxy/files/mcproxy.init
mcproxy/patches/0004-uclibc-add-defs.patch

mcproxy: update to latest version, add UCI support

---

bird/Makefile

Based on pull request https://github.com/openwrt-routing/packages/pull/42 by MartinStrbacka.

bird: add lightweight client support

---

bmx6/patches/001-json-c.patch

bmx6: fix json.h include

---

bmx6/Makefile

bmx6: fix libjson-c dependency

---

cjdns/Makefile
cjdns/files/cjdns.defaults
cjdns/files/cjdns.init
cjdns/files/cjdrouteconf
cjdns/lua/cjdns/admin.lua
cjdns/lua/cjdns/common.lua
cjdns/lua/cjdns/init.lua
cjdns/lua/cjdns/uci.lua
cjdns/lua/cjdns/udp.lua
cjdns/patches/010-fix-musl-build.patch

cjdns: import package from github.com:SeattleMeshnet/meshbox

---

luci-app-cjdns/Makefile
luci-app-cjdns/luasrc/controller/cjdns.lua
luci-app-cjdns/luasrc/model/cbi/cjdns/cjdrouteconf.lua
luci-app-cjdns/luasrc/model/cbi/cjdns/iptunnel.lua
luci-app-cjdns/luasrc/model/cbi/cjdns/overview.lua
luci-app-cjdns/luasrc/model/cbi/cjdns/peering.lua
luci-app-cjdns/luasrc/model/cbi/cjdns/settings.lua
luci-app-cjdns/luasrc/view/admin_status/index/cjdns.htm
luci-app-cjdns/luasrc/view/cjdns/status.htm
luci-app-cjdns/luasrc/view/cjdns/value.htm

luci-app-cjdns: import package from SeattleMeshnet/meshbox

---

nat46/Makefile
nat46/src/464xlatcfg.c

Signed-off-by: Hans Dedecker <dedeckeh@gmail.com>

nat46: Refuse link local address as implicit source in 464xlat

---

cjdns/Makefile

cjdns: package test cases

---

oonf-dlep-proxy/Makefile
oonf-dlep-proxy/files/dlep_proxy.hotplug
oonf-dlep-proxy/files/dlep_proxy.init
oonf-dlep-proxy/files/dlep_proxy.uci
oonf-dlep-radio/Makefile
oonf-dlep-radio/files/dlep_radio.hotplug
oonf-dlep-radio/files/dlep_radio.init
oonf-dlep-radio/files/dlep_radio.uci
oonf-olsrd2/Makefile
oonf-olsrd2/files/olsrd2.hotplug
oonf-olsrd2/files/olsrd2.init
oonf-olsrd2/files/olsrd2.uci

This are "fixed version" build files for v0.8.2, not "rolling git" ones. I compile-tested them with barrier breaker and chaos calmer. I also tested the olsrd2 barrier breaker executable on a Ubiquity Bullet M5.

Add v0.8.2 OONF build files

---

nat46/files/464xlat.sh

Signed-off-by: Hans Dedecker <dedeckeh@gmail.com>

nat46: Fix 464xlat interface teardown

---

bird/Makefile

bird: update to v1.5.0, add myself as maintaner

---

olsrd/files/olsrd.init

Backport from master, make ipv6only option boolean in olsrd init script.

make ipv6only boolean in olsrd init, backport from master

---

olsrd/files/olsrd.init

Requested by bittorf in https://github.com/openwrt-routing/packages/pull/155

Replace == operator in test with = operator.

---

alfred/Makefile

upgrade package to latest release 2016.0

Alfred 2016.0

---

miniupnpd/Makefile

1.9 has bugs please update
https://github.com/openwrt/packages/issues/2889

miniupnpd-2.0

---

miniupnpd/patches/101-no-ssl-uuid.patch
miniupnpd/patches/102-ipv6-ext-port.patch
miniupnpd/patches/103-no-ipv6-autodetection.patch

Refresh patches to clear patch fuzz
Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

miniupnpd: refresh patches

---

olsrd/Makefile

version numkber now on 0.9.5
netjson plugin added

olsrd: new version number 0.9.5 and new netjson plugin

---

babeld/Makefile
babeld/files/babeld.init

Based on the work of @imuli with some changes.

babeld: Add procd support and other fixes

---

MAINTAINERS
babeld/Makefile

As discussed in #250 .
Also update my email address in the main MAINTAINERS file.

babeld: Add myself as maintainer

---

bird/Makefile

bird: update to v1.6.3

---

olsrd/Makefile

olsrd: Makefile - remove empty line

---

poprouting/Makefile

same as https://github.com/openwrt-routing/packages/pull/263

Lede 17.01

---

miniupnpd/Makefile

Update miniupnpd to 2.0.20170421
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

miniupnpd: Update to 2.0.20170421

---

nat46/Makefile
nat46/files/464xlat.sh
nat46/src/464xlatcfg.c

Make 464xlat work again after it was broken due to changes in netifd

Rework 464xlat

---

nodogsplash2/Makefile
nodogsplash2/files/nodogsplash.config
nodogsplash2/files/nodogsplash.init

This package is a transitional package for nodogsplash, so that the old version is still available for those who miss features that have not yet been implemented.

nodogsplash2: initial package

---

batman-adv/files/compat-hacks.h

@simonwunderlich @dangowrt @hauke

batman-adv: Fix conflicts with compat-wireless backports-4.14-rc1

---

cjdns/Makefile
cjdns/lua/cjdns/uci.lua

PR from #335 with different commit history.
> Because author of #320, #321 is unresponsive. I try to fix minor issues and reply PR, it contains important updates for Hyperboria.net community. Please merge as soon as possible.

cjdns: update to version 0.20

---

mcproxy/Makefile

mcproxy: update to latest version

---

ndppd/Makefile

Maintainer: @kerneis 
Fix source URL for the 15.05 branch.

CC: ndppd: fix source URL

---

luci-app-cjdns/Makefile
luci-app-cjdns/luasrc/controller/cjdns.lua
luci-app-cjdns/luasrc/view/cjdns/status.htm

* adds layer 2 and 3 address display column
* fixes switch label pinger
* get version from addr string
* parse addr string for peerStats publicKey

luci-app-cjdns: luci admin support for cjdns-v20.2

---

alfred/Makefile
batctl/Makefile
batman-adv/Config.in
batman-adv/Makefile
batman-adv/files/etc/config/batman-adv

@simonwunderlich : As discussed, this are the backported changes from #420 and #421 (only the first fix). See these pull requests for more details.

openwrt-18.06: batman-adv package fixes

---

cjdns/Makefile
mcproxy/Makefile
mcproxy/patches/0003-add-sourcefilter.patch
mcproxy/patches/0004-add-defs.patch

https://downloads.openwrt.org/snapshots/faillogs/arc_archs/routing/

Build fixes

---

mcproxy/files/mcproxy.config
mcproxy/patches/0003-add-sourcefilter.patch
mcproxy/patches/0005-fix-match-filter-calls.patch
mcproxy/patches/0006-block-ingress.patch
mcproxy/patches/0007-igmpv2-queries.patch

This PR contains 2 patches provided by members of prpl.

mcproxy: some add some fixes

---

babeld/Makefile
babeld/files/babeld.config
babeld/files/babeld.init

It will be nice to have the latest version of babeld in the upcoming 19.07 release.

[openwrt-19.07] babeld: Update to 1.9.1 and assorted fixes

---

bmx7/Makefile
bmx7/files/etc/config/bmx7
bmx7/files/etc/init.d/bmx7

Also clean up the Makefile
Signed-off-by: Paul Spooren <mail@aparcar.org>

bmx7: update to 7.1.1

---

cjdns/Makefile
luci-app-cjdns/Makefile

cjdns: luci-app-cjdns: fix up Makefiles, bump pkg vers

---

luci-app-bmx6/bmx6/usr/lib/lua/luci/view/admin_status/index/neighbours_simple.htm

see 51b370e1ce4e55e8ac333d57cc6709309eeffcdc and #550

luci-app-bmx6: bugfix querying bmx6-info (p2)

---

luci-app-cjdns/Makefile
luci-app-cjdns/files/luci-app-cjdns.json

luci-app-cjdns: Add rpcd acl file

---

luci-app-bmx6/bmx6/www/cgi-bin/bmx6-info

Signed-off-by: Pedro <pedrowrt@cas.cat>

luci-app-bmx6: fixes error line in logread #578

---

nodogsplash/Makefile

nodogsplash: update to 5.0.0

---

bmx7/Makefile
bmx7/patches/010-gcc10.patch

bmx7: fix compilation with GCC 10

---

bird2/Makefile
bird2/patches/010-gcc10.patch

bird2: fix compilation with GCC 10

---

olsrd/Makefile
olsrd/patches/010-musl.patch

olsrd: fix compilation with musl 1.2.x

---

oonf-dlep-radio/patches/010-gcc10.patch

oons-dlep-radio: fix compilation with GCC 10

---

oonf-olsrd2/patches/010-gcc10.patch

oons-olsrd2: fix compilation with GCC 10

---

bird1/Makefile
bird1/patches/010-gcc10.patch

bird1: fix compilation with GCC 10

---

prince/Makefile
prince/patches/010-gcc10.patch

prince: fix compilation with GCC 10

---

bmx7/Makefile
bmx7/patches/020-siocgstamp.patch

bmx7: fix compilation with uClibc-ng

---

.github/issue_template
.github/pull_request_template
.github/workflows/Dockerfile
.github/workflows/ci_helpers.sh
.github/workflows/entrypoint.sh
.github/workflows/formal.yml
.github/workflows/multi-arch-test-build.yml

Just copy .github from openwrt enabling:
- checking of formalities
- checking of build
- issue template
- pr template

CI: copy .github from openwrt-packages

---

olsrd/Makefile
olsrd/patches/000-filtergw.patch

Olsrd filtergw

---

olsrd/Makefile

This reverts commit a46eb8b8426c023bf502ed04671fa416ebc98de5.

Revert "olsrd: use SPDX and bump copyright"

---

babeld/Makefile
babeld/patches/600-add-ubus.patch
babeld/src/ubus.c

Runtested: 21.02 OpenWrt Fritz!Box 7530 (ipq40xx)

[21.02] babeld: pull latest changes

---

olsrd/files/olsrd4.init
olsrd/files/olsrd6.init

Fixes:
https://github.com/openwrt/luci/issues/5139

olsrd: reload if config changed via uci

---

olsrd/files/olsrd4.init
olsrd/files/olsrd6.init

Fixes:
https://github.com/openwrt/luci/issues/5139

[21.02] olsrd: reload if config changed via uci

---

olsrd/files/olsrd4.init
olsrd/files/olsrd6.init

olsrd: fix olsrd starting before network

---

olsrd/files/olsrd.config
olsrd/files/olsrd4.init
olsrd/files/olsrd6.config
olsrd/files/olsrd6.init

Also make respawn_threshold configurable. Further, add default values for:
- respawn_threshold 3600
- respawn_timeout 15
- respawn_retry 0

olsrd: make respawn_threshold configurable

---

olsrd/files/olsrd.config
olsrd/files/olsrd4.init
olsrd/files/olsrd6.config
olsrd/files/olsrd6.init

It was requested to name the section "procd".

olsrd: rename general to procd

---

alfred/Makefile
batctl/Makefile
batman-adv/Makefile

Revert "batman-adv: update packages to version 2021.4"

---

batman-adv/patches/0006-batman-adv-fix-error-handling.patch

Description:
* fix error handling during interface initialization

openwrt-21.02: batman-adv: Merge bugfixes from 2021.4

---

babeld/src/ubus.c
babeld/src/ubus.h

[21.02] babeld: backport changes

---

opennds/Makefile

Maintainer: @bluewavenet
Compile & run tested:  N/A just moving rows
Description:
- Switch to AUTORELEASE
- Reorder things
- Fixed SPDX License Identifier
- Added PKG_LICENSE_FILES
- Use two spaces instead of tab

opennds: Makefile refactoring

---

quagga/Makefile
quagga/patches/200-gcc10.patch

Maintainer: unknown / not active
Compile tested: no, just reordering things
Run tested: no
Description:
- Fix SPDX License Identifier
- Use HTTPS in URL
cc: @neheb is this reordered correctly?

quagga: reorder things in Makefile

---

olsrd/Makefile

Maintainer: @PolynomialDivision 
Compile tested: no
Run tested: no

olsrd: fix recursive dependency

---

bird2/Makefile
bird2/files/bird.init

Compile tested: NA
Run tested: NA

bird2: stop service early

---

babeld/Makefile

Changelog:
916d3d9 Update CHANGES for babeld-1.12.1
3d8aec4 Schedule an interface check after adding an interface.
f13602b Split last PC into unicast and multicast values

babled: update to 1.12.1

---

naywatch/files/naywatch.sh

Naywatch now prints
naywatch: Naywatch Activated!
when becoming active.

naywatch: add log when naywatch activates

---

cjdns/Makefile
cjdns/lua/cjdns/uci.lua
luci-app-cjdns/Makefile
luci-app-cjdns/luasrc/model/cbi/cjdns/peering.lua

(cherry picked from commit d705f7989080f38feba4329e5f24d2c85f99a902)

[22.03] cjdns: support the supernodes feature (#884)

---

cjdns/Makefile
cjdns/lua/cjdns/uci.lua
luci-app-cjdns/Makefile
luci-app-cjdns/luasrc/model/cbi/cjdns/peering.lua

(cherry picked from commit d705f7989080f38feba4329e5f24d2c85f99a902)

[21.02] cjdns: support the supernodes feature (#884)

---

olsrd/patches/102-limit-valid-+ve-sequence-number-diff-to-avoid-storms.patch

Fixes:
https://github.com/OLSR/olsrd/issues/106

olsrd: import patch to prevent olsr storms

---

olsrd/patches/102-olsrd-prevent-storm-patches.patch

Fixes: bb5bbc6afd8c ("olsrd: import patch to prevent olsr storms")

[22.03] olsrd: replace patch for storms with real patch

---

olsrd/Makefile

Maintainer: @PolynomialDivision 
Compile tested: n/a
Run tested: n/a

olsrd: trim trailing space

---

batman-adv/patches/0012-batman-adv-Fix-hang-up-with-small-MTU-hard-interface.patch

batman-adv
==========
* Fix hang up with small MTU hard-interface

openwrt-22.03: batman-adv: Merge bugfixes from 2022.3

---

batman-adv/patches/0015-batman-adv-Fix-hang-up-with-small-MTU-hard-interface.patch

batman-adv
==========
* Fix hang up with small MTU hard-interface

openwrt-21.02: batman-adv: Merge bugfixes from 2022.3

---

bird2/Makefile

Signed-off-by: Bradford Zhang <zyc@zyc.name>
Maintainer: @tohojo

bird2: bump to version 2.0.11

---

bird1-openwrt/bird1-ipv4-openwrt/Makefile
bird1-openwrt/bird1-ipv6-openwrt/Makefile

Maintainer: @eloicaso
Description:
As discussed and agreed here https://github.com/openwrt/routing/pull/900, the maintainer will be changed from @eloicaso to @rogerpueyo
Please review and give a quick OK. Then we can merge.

bird1-openwrt: change maintainer

---

babeld/Makefile

babeld: remove AUTORELEASE

---

bird2/Makefile

Maintainer:  @tohojo
Description:

bird2: bump to version 2.0.12

---

.github/workflows/check-autorelease-deprecation.yml
.github/workflows/entrypoint.sh
.github/workflows/multi-arch-test-build.yml

Sync with latest changes on openwrt/packages.

ci: sync with latest openwrt/packages

---

.github/workflows/check-autorelease-deprecation.yml
.github/workflows/entrypoint.sh
.github/workflows/multi-arch-test-build.yml

Maintainer: noone
Compile tested: ci
Run tested: ci
Backported from https://github.com/openwrt/routing/pull/946

[23.05] CI - GitHub actions sync with the latest changes from OpenWrt packages repository

---

oonf-init-scripts/files/oonf_init.sh
oonf-olsrd2/Makefile
oonf-olsrd2/files/olsrd2.init

[23.05]: oonf-olsrd2: add support to check if service is running

---

batman-adv/Makefile
batman-adv/patches/0016-batman-adv-fix-panic-during-interface-removal.patch
batman-adv/patches/0017-batman-adv-Ignore-neighbor-throughput-metrics-in-err.patch
batman-adv/patches/0018-batman-adv-Drop-unmanaged-ELP-metric-worker.patch

Description:
* force stop of throughput detection workers on interface removal

openwrt-23.05: batman-adv: Merge bugfixes from 2025.0

---

bird3/Makefile

Release Notes:
https://bird.network.cz/pipermail/bird-users/2025-April/018156.html
Maintainer: me, @tohojo 
Compile tested: filogic

bird3: update to 3.1.0

---

bird2/Makefile

Release Notes:
https://bird.network.cz/pipermail/bird-users/2025-April/018156.html
Maintainer: me, @tohojo 
Compile tested: filogic

bird2: update to 2.17

---

bird2/Makefile

Release Notes:
https://bird.network.cz/pipermail/bird-users/2025-May/018195.html
Compile tested: qoriq

bird2: update to 2.17.1

---

babel-pinger/Makefile

Maintainer: @kerneis 
Compile tested: NO

Improve babel-pinger Makefile

---

batman-adv/Makefile
batman-adv/patches/0020-batman-adv-fix-duplicate-MAC-address-check.patch

Description:
* fix duplicate MAC address check

openwrt-23.05: batman-adv: Merge bugfixes from 2025.2

---

bird2/Makefile
bird3/Makefile

Maintainer: @tohojo , @PolynomialDivision
This is just a few things, which I modify, before these two packages can be moved to the packages feed.

bird{2,3}: improve Makefile

---

bird3/Makefile

Release Notes:
- 3.1.1: https://bird.network.cz/pipermail/bird-users/2025-May/018199.html
- 3.1.2: https://bird.network.cz/pipermail/bird-users/2025-May/018245.html
Maintainer: @tohojo, me
Compile tested: ath79

bird3: update to 3.1.2
