openwrt/routing

- olsrd/files/olsrd.init
olsrd 0.6.8 accepts a PingCmd parameter as of
http://olsr.org/git/?p=olsrd.git;a=commitdiff;h=0a26c52af3941eb9060b193cae5552f8d13fd28e.
The PingCmd is a string of the form "ping -c 1 -q %s" where %s is
replaced with an IP. This commit allows for '%' characters in an olsrd
option.
> [olsrd] adapt init script for 0.6.8 (PingCmd option)

- nodogsplash/Makefile
- nodogsplash/files/nodogsplash.init
- nodogsplash/files/nodogsplash.migrate
Use /etc/config/nodogsplash for configuration.
Old setups will migrate using config option to use old
file base configuration.
> nodogsplash: migrate to uci based configuration

- mcproxy/Makefile
- mcproxy/files/mcproxy.init
- fix /var/etc race condition (uci config)
- start mcproxy later
- rework mcproxy config trigger
- add network triggers
- simplify uci instances generation and allow querier only configs
- improve uci tables generation
- fix uci behaviour generation for specific interface names
> mcproxy: uci config improvements and fixes

- nat46/src/464xlatcfg.c
This avoids warning traces like "Can not add: device clat already exists!" when the clat interface is brought up again after previously being brought down
> nat46: Delete 464xlat device when pause is interrupted by SIGTERM

- cjdns/Makefile
Properly pass UCLIBC=1 only in case we are actually building with uClibc. Fixes SSP support at least on musl (and probably glibc).
> cjdns: support libc other than uClibc

- cjdns/files/cjdns.defaults
rant-mode=on: Generally, Linux interface names should not leak into uci, uci interfaces should be used instead (i.e. lan instead of eth0 or br-lan)
cjdrouteconf should query this from netifd via ubus similar to
ubus call network.interface status "{ \"interface\" : \"lan\" }"
> Some uci defaults fixes

- babeld/files/babeld.init
Without this automatic init script activation in imagebuilder fails.
> babeld: Added missing $IPKG_INSTROOT

- alfred/files/alfred.init
For reference:
```
$alfred -h
-b                                  specify the batman-adv interface
configured on the system (default: bat0)
use 'none' to disable the batman-adv
based best server selection
```
> alfred: do not handle 'none' as an existing interface

- olsrd/files/olsrd.init
Without this, the value will be written as '0' or '1' to the generated configs while it should be 'no' or 'yes'. Please also cherry pick this change for the for-15.05 branch.
> make ipv6only plugin option boolean in init functions

- babeld/files/babeld.config
- babeld/files/babeld.init
When parsing list options using config_load option_cb will be called
with additional options ending in _ITEM$x and _LENGTH. This ignores any
option containing _LENGTH or _ITEM as they can't possible be a valid
babeld option making a config like
config general
list import_table 23
list import_table 42
work.
Signed-off-by: Nils Schneider <nils@nilsschneider.net>
> babeld: fix parsing of list import_table

- bird/Makefile
fixes gcc5 compile
compile error was:
cf-lex.o: In function `add_tail':
cf-lex.c:(.text+0x2d1): multiple definition of `add_tail'
cf-parse.tab.o:cf-parse.tab.c:(.text+0x1f9): first defined here
Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>
> bird: explicitly set C standard

- alfred/files/alfred.init
Changes between alfred 2015.0 and 2015.1 cause alfred to print an error
and exit when the interface to bind to is not completely set up (has no
non-tentative link-local address). As a workaround, wait for such an
address by reading /proc/net/if_inet6 before alfred is started.
In the long term, it would be nice to make alfred more robust against
missing interfaces (allowing alfred to start without the interface
existing, and keeping it working even when the interface is removed and
re-added while alfred is running).
Signed-off-by: Matthias Schiffer <mschiffer@universe-factory.net>
> alfred: not only wait for the interface, but also a link-local address

- olsrd/files/olsrd.init
Restarting olsrd for IPv6 clears SmartGateway firewall rules for both IPv4
and IPv6, and does not restore the IPv4 rules. As a result, IPv4 SmartGateway
functionality is broken after /etc/init.d/olsrd6 restart.
> Fix '/etc/init.d/olsrd6 restart' breaks IPv4 SmartGateway.

- bird/Makefile
- bird/patches/001-netlink-update-struct-msghdr.patch
* Fix recvmsg/sendmsg on mips64
* Bump to 1.6.0
> bird: fix mips64, bump to 1.6.0

- batman-adv/Makefile
kmod-crypto-core was removed in openwrt/trunk svn 46820 and all
kconfig's are now built-in.
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>
> batman-adv: remove DEPENDS:=kmod-crypto-core

- cjdns/Makefile
By default, cjdns' build system uses the system wide `/tmp` directory to store
intermediate build artifacts.
Unfortunately its build system fails to clean after itself, leaving thousands
of `jsmake-<hash>` directories behind, taking up precious inodes and massively
slowing down processes traversing the temporary directory:
root@buildbot:~# find /tmp/ -maxdepth 1 -type d -name 'jsmake-*' | wc -l
1581
Attempt to solve that problem by using the upstream-introduced
`CJDNS_BUILD_TMPDIR` environment variable in order to move the intermediate
artifacts from the system-wide `/tmp` to a temporary directory within the
package build dir which is properly deleted upon package rebuild cycles.
Signed-off-by: Jo-Philipp Wich <jo@mein.io>
> cjdns: use temporary directory within the build environment

- oonf-init-scripts/files/oonf_hotplug.sh
The current quoting did not allow substitution and resulted in log messages with
the prefix "${DAEMON}[hotplug]".
> fix quoting of daemon name

- nat46/Makefile
Signed-off-by: Hans Dedecker <dedeckeh@gmail.com>
> nat46: Depend on IPV6 as IPv6 is kernel builtin module now

- hnetd/files/hnet.config
- hnetd/files/hnetd.init
Add support for setting the `ip4mode` parameter (sbyx/hnetd@2953f5a) in
the `config pa pa` stanza of `/etc/config/hnet`.
> hnetd: support the ip4mode parameter

- batman-adv/patches/0001-batman-adv-Avoid-nullptr-dereference-in-bla-after-vl.patch
- batman-adv/patches/0002-batman-adv-Avoid-nullptr-dereference-in-dat-after-vl.patch
- batman-adv/patches/0003-batman-adv-Avoid-tt_req_node-list-put-for-unhashed-e.patch
- batman-adv/patches/0004-batman-adv-Fix-orig_node_vlan-leak-on-orig_node_rele.patch
- batman-adv/patches/0005-batman-adv-Fix-non-atomic-bla_claim-backbone_gw-acce.patch
- batman-adv/patches/0006-batman-adv-Fix-reference-leak-in-batadv_find_router.patch
- batman-adv/patches/0007-batman-adv-Free-last_bonding_candidate-on-release-of.patch
- batman-adv/patches/0008-batman-adv-Fix-speedy-join-in-gateway-client-mode.patch
Speedy join only works when the received packet is either broadcast or an 4addr unicast packet. Thus packets converted from broadcast to unicast via the gateway handling code have to be converted to 4addr packets to allow the receiving gateway server to add the sender address as temporary entry
to the translation table.
Not doing it will make the batman-adv gateway server drop the DHCP response in many situations because it doesn't yet have the TT entry for the destination of the DHCP response.
> batman-adv: Fix speedy join in gateway client mode

- batman-adv/patches/0001-batman-adv-Avoid-nullptr-dereference-in-bla-after-vl.patch
- batman-adv/patches/0002-batman-adv-Avoid-nullptr-dereference-in-dat-after-vl.patch
- batman-adv/patches/0003-batman-adv-Avoid-tt_req_node-list-put-for-unhashed-e.patch
- batman-adv/patches/0004-batman-adv-Fix-orig_node_vlan-leak-on-orig_node_rele.patch
- batman-adv/patches/0005-batman-adv-Fix-non-atomic-bla_claim-backbone_gw-acce.patch
- batman-adv/patches/0006-batman-adv-Fix-reference-leak-in-batadv_find_router.patch
- batman-adv/patches/0007-batman-adv-Free-last_bonding_candidate-on-release-of.patch
* Avoid nullptr dereference in bla after vlan_insert_tag
* Avoid nullptr dereference in dat after vlan_insert_tag
* Avoid tt_req_node list put for unhashed entry
* Fix orig_node_vlan leak on orig_node_release
* Fix non-atomic bla_claim::backbone_gw access
* Fix reference leak in batadv_find_router
* Free last_bonding_candidate on release of orig_node
> batman-adv: Add reference counting + nullptr fixes

- batman-adv/patches/0015-batman-adv-Avoid-nullptr-dereference-in-bla-after-vl.patch
- batman-adv/patches/0016-batman-adv-Avoid-nullptr-dereference-in-dat-after-vl.patch
- batman-adv/patches/0017-batman-adv-Avoid-tt_req_node-list-put-for-unhashed-e.patch
- batman-adv/patches/0018-batman-adv-Fix-orig_node_vlan-leak-on-orig_node_rele.patch
- batman-adv/patches/0019-batman-adv-Fix-non-atomic-bla_claim-backbone_gw-acce.patch
- batman-adv/patches/0020-batman-adv-Fix-reference-leak-in-batadv_find_router.patch
- batman-adv/patches/0021-batman-adv-Free-last_bonding_candidate-on-release-of.patch
* Avoid nullptr dereference in bla after vlan_insert_tag
* Avoid nullptr dereference in dat after vlan_insert_tag
* Avoid tt_req_node list put for unhashed entry
* Fix orig_node_vlan leak on orig_node_release
* Fix non-atomic bla_claim::backbone_gw access
* Fix reference leak in batadv_find_router
* Free last_bonding_candidate on release of orig_node
> CC: batman-adv: Add reference counting + nullptr fixes

- miniupnpd/Makefile
- miniupnpd/files/firewall.include
add MINIUPNPD-POSTROUTING rule. Solves following error
addmasqueraderule() : chain MINIUPNPD-POSTROUTING not found
Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>
> miniupnpd: add igd2 postrouting table

- ndppd/Makefile
Looks like http://www.priv.nu is offline for eternity.
[Tested on Entware-ng](https://github.com/Entware-ng/entware-routing/commit/16cd0418a3077a81018e335c2d73da2571bf1a44).
> ndppd: fix source URL

- babeld/Makefile
There is a HTTP redirection in place from the old URL to the new URL, but
better change it now than waiting for the redirection to disappear.
Signed-off-by: Baptiste Jonglez <git@bitsofnetworks.org>
> babeld: Update source URL

- batman-adv/Makefile
The build of netlink.c in batman-adv 2016.3 will fail because the definition of GENL_NAMESIZE and similar things are missing. This is is caused by an incorrect order of backports and non-backports header files mixed up with uapi and non-uapi header files. Parts of the header files would not get included by include_next because it not anymore in the remaining search paths.
> batman-adv: Exchange include order for uapi header files

- batman-adv/Makefile
- batman-adv/files/compat-hacks.h
The CONFIG_MODULE_STRIPPED hack broke some time ago, as it is undefined too
late (after the headers using it have been included by compat-hacks.h).
Undefine CONFIG_MODULE_STRIPPED at the top of compat-hacks.h instead to
make the module version available to batctl again.
Signed-off-by: Matthias Schiffer <mschiffer@universe-factory.net>
@lindnermarek
> batman-adv: move CONFIG_MODULE_STRIPPED hack to compat-hacks.h

- miniupnpd/Makefile
- miniupnpd/files/miniupnpd.hotplug
- miniupnpd/files/miniupnpd.init
* Remove 'local' variable definitions from hotplug script's main body.   This fixes #231
Busybox 1.25.0 does not allow local variables defined outside functions. LEDE is already using 1.25.0 and I noticed the problem, when miniupnpd started a regular logspam. (Apparently Busybox throws error and leaves the possible value assignment undone.)
* Change startup priority slightly from 95 to 94, so that miniupnpd starts before S95done (which is intended to be run last). With the current value 95, the /etc/rc.d symlink for miniupnpd is S95miniupnpd that gets run after S95done.
maintainer: @fingon
> miniupnpd: fix local variables in hotplug script, change startup priority slightly

- babeld/Makefile
this means that babeld (especially the interfaces it uses) may be reconfigured during runtime.
> update babeld to version 1.8 which is compatible to 1.7.1 and adds a rw socket

- olsrd/patches/missing-include-dirs-warning.patch
remove this warning as it fails to build for the nmealib with missing
"staging_dir/target-mipsel_24kc_musl-1.1.15/include" from buildenv
this fixes #244 on OpenWrt + LEDE master (checked via SDK-build)
> olsrd: disable compiler-warning "missing-include-dirs"

- miniupnpd/Makefile
- miniupnpd/patches/105-enable_check_portinuse.patch
- miniupnpd/patches/106-enable_igdv2.patch
Enable IGDv2 as v1 Device DCPs were deprecated as of March 30, 2015
Source: http://upnp.org/specs/gw/igd2
Enable port in use check
Patches are originally from the FreeBSD Ports repo and refreshed for this repo.
Source: https://svnweb.freebsd.org/ports/head/net/miniupnpd/files/
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>
> miniupnpd: Update to 2.0.20161216

- babeld/Makefile
- babeld/files/babeld.init
It makes the init script more readable.  It has been more than two years
since babeld 1.5.1, let's hope nobody is still using the old
(undocumented) option names.
Incidentally, this commit fixes support for the "conf_dir" option,
introduced by ac643416dc ("babeld: allow changing alternative
configuration file and directory").  The default value of $OTHERCONFIGDIR
was always used, because the variable was used *before* it was (possibly)
redefined when parsing the UCI config.
Signed-off-by: Baptiste Jonglez <git@bitsofnetworks.org>
> babeld: Cleanup old compatibility code in initscript

- olsrd/files/olsrd.init
It's announced since several years (mid of 2014), that such setups (one olsrd running IPv4 and IPv6) will no be supported anymore. There seems to have been enough time to implement the required changes.
Comparing the generated configfile shows that they are equal. Only the IPv6-config has an "IpVersion 6" setting added now
> Olsrd: remove 6and4 backward compatibility

- ndppd/patches/0002-upstream-cast-fix.patch
Import upstream commit "f19fa4b Fix a cast so it can be compiled with gcc-6"
in order to fix building ndppd with recent gcc versions.
Fixes the following error spotted by the build bots:
src/iface.cc: In static member function 'static ndppd::ptr<ndppd::iface> ndppd::iface::open_pfd(const string&)':
src/iface.cc:153:5: error: narrowing conversion of '-1' from 'int' to '__u32 {aka unsigned int}' inside { } [-Wnarrowing]
Signed-off-by: Jo-Philipp Wich <jo@mein.io>
> ndppd: fix compilation with modern gcc

- poprouting/Makefile
Hi, i would like to add my [implementation](https://github.com/gabri94/poprouting) for Pop-Routing to openwrt.
It is a demon used to optimize the timer's value of OONF, so i think it belongs to the routing feed.
I developed it as GSoC 2016 project with Freifunk and Ninux. 
Unfortunately due to a C++ Library the v0.1 version wasn't installable on embedded devices. (2MB of size)
Recently we've re-implemented this library in pure C and the new version (v0.2) has a tinier packet (20KB).
Thanks, Gabriel
> Add Prince to openwrt-routing

- batman-adv/Makefile
@ecsv @lindnermarek
Please also apply to lede-17.01.
The batman-adv Makefile set a PKG_BUILD_DIR outside of KERNEL_BUILD_DIR;
this could lead to batman-adv not being rebuilt when switching targets and
thus kernel configurations. This resulted in ABI mismatches and
occasionally broke the build with messages like the following:
Package kmod-batman-adv is missing dependencies for the following libraries:
crc16.ko
Instead of setting a better PKG_BUILD_DIR ourselves, we can just remove
the explicit PKG_BUILD_DIR definition and include kernel.mk before
package.mk to get the default definition used by other kernel module
packages.
Reported-by: David Lutz <kpanic@hirnduenger.de>
Signed-off-by: Matthias Schiffer <mschiffer@universe-factory.net>
> batman-adv: use kernel-specific PKG_BUILD_DIR

- batman-adv/Config.in
@simonwunderlich @ecsv
Compile BATMAN V per default to make the routing algorithm available in the snapshot builds and release packages.
Signed-off-by: Marek Lindner <mareklindner@neomailbox.ch>
> batman-adv: compile batman v by default

- miniupnpd/files/miniupnpd.init
- miniupnpd/files/upnpd.config
Add a 'master' miniupnpd service enable flag rather than just relying on
rcS.d script existence.  This allows the service to be disabled across
sysupgrade, similar to minidlna.
The service assumes enabled if no 'enabled' config flag is configured
for backwards compatibility.
Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>
> miniupnpd: implement an 'enabled' flag

- miniupnpd/Makefile
The upstream project also reverted IGDv2-by-default due to widespread
compatibility problems.
So far all Microsoft operating systems up to Windows 10, Xbox 360, Xbox One
Playstation 3 and Playstation 4 consoles seem to be incompatible to the
new 2.0 standard.
Signed-off-by: Jo-Philipp Wich <jo@mein.io>
> miniupnpd: disable IGDv2 by default

- batman-adv/files/compat-hacks.h
-----
batman-adv must make sure that ether_setup is already declared via linux/netdevice.h before the preprocessor can patch the use of it in batman-adv. Otherwise it is tried to also patch the declaration of
ether_setup.
Fixes: 8da2f5cbb128 ("batman-adv: upgrade package to latest release 2017.2")
> batman-adv: Prevent FTBFS when redefining ether_setup

- smcroute/Makefile
- smcroute/patches/001-Make-output-of-build-id-optional.patch
The build id contains the build timestamp by default.
Make this field optional.
Build timestamp prevents reproducible builds [0].
Thanks to the debian project for the patch.
[0] https://reproducible-builds.org/docs/timestamps/
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>
> smcroute: make build id optional

- olsrd/Makefile
BTW According to Matthias there is no ncurses package either way!
Signed-off-by: Ferry Huberts <ferry.huberts@pelagic.nl>
> olsrd: pud: does not depend on ncurses

- mcproxy/patches/0001-add-cmake.patch
Signed-off-by: Stefan Peter <s.peter@mpl.ch>
--
Building mcproxy with musl fails:
[ 45%] Building CXX object CMakeFiles/mcproxy-bin.dir/mcproxy/src/proxy/proxy_instance.cpp.o
In file included from /opt/mpl/GUARD64/LEDE/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.16/lib/gcc/x86_64-openwrt-linux-musl/5.4.0/include/xmmintrin.h:34:0,
from /opt/mpl/GUARD64/LEDE/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.16/lib/gcc/x86_64-openwrt-linux-musl/5.4.0/include/x86intrin.h:31,
from /opt/mpl/GUARD64/LEDE/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.16/x86_64-openwrt-linux-musl/include/c++/5.4.0/x86_64-openwrt-linux-musl/bits/opt_random.h:33,
from /opt/mpl/GUARD64/LEDE/staging_dir/toolchain-x86_64_gcc-5.4.0_musl-1.1.16/x86_64-openwrt-linux-musl/include/c++/5.4.0/random:50,
from …
> mcproxy: remove pedantic flag to allow compilation with musl

- nodogsplash2/files/nodogsplash.config
nodogsplash2: changes to defaults.
List of changes:
1. Set default to NoDogsplash enabled as rest of config should now be safe and is possible to SSH to router to stop NDS if needed
2. Change clientidletimeout to 120 minutes (2 hours)
3. Add clientforcetimeout set to 1440 minutes (24 hours)
4. Comment out the two provided example authenticated_users block lines
5. Add  list authenticated_users 'allow all'
6. Comment out original list authenticated_users 'allow... entries leaving as example.
7. Preauth default set to block remote DNS. All devices used at public wifi venues should be configured for DHCP. Forcing use of the local DNS server makes DNS tunnelling very inefficient if not unusable on a typical OpenWrt/LEDE device.
8. Add new fw_mark settings for compatibility with other OpenWrt …
> nodogsplash2: change configuration defaults

- batman-adv/files/compat-hacks.h
> batman-adv: Fix missing function name for timer_setup in compat-hacks

- nodogsplash2/files/nodogsplash.config
This change will fix a problem where NoDogSplash2 Fails to start if the device it binds to is not ready.
> nodogsplash2: Fix Startup Failure

- nat46/Makefile
- nat46/files/464xlat.sh
Quit the teardown function in case the file 464-$cfg-anycast is not
present as it means no clean up of ip rules is required.
It fixes error traces like "cat: can't open '/tmp/464-wan6_4-anycast':
No such file or directory" and "Error: inet6 prefix is expected rather
than "lookup"."
At the same time remove the unused variable anycast_active.
Signed-off-by: Hans Dedecker <dedeckeh@gmail.com>
> nat46: harden 464xlat teardown logic

- bmx6/Makefile
- bmx7/Makefile
@axn please add PKG_MIRROR_HASH when using larger git repos to reduce traffic and load on the buildbots.
> bmx6/7: add pkg mirror hash

- batman-adv/patches/0024-batman-adv-fix-packet-checksum-in-receive-path.patch
- batman-adv/patches/0025-batman-adv-invalidate-checksum-on-fragment-reassembl.patch
- batman-adv/patches/0026-batman-adv-Ignore-invalid-batadv_iv_gw-during-netlin.patch
- batman-adv/patches/0027-batman-adv-Ignore-invalid-batadv_v_gw-during-netlink.patch
- batman-adv/patches/0028-batman-adv-Fix-netlink-dumping-of-BLA-claims.patch
- batman-adv/patches/0029-batman-adv-Fix-netlink-dumping-of-BLA-backbones.patch
- batman-adv/patches/0030-batman-adv-Fix-internal-interface-indices-types.patch
batman-adv
==========
* fix packet checksum in receive path
* invalidate checksum on fragment reassembly
* Ignore invalid batadv_iv_gw during netlink send
* Ignore invalid batadv_v_gw during netlink send
* Fix netlink dumping of BLA claims
* Fix netlink dumping of BLA backbones
* Fix internal interface indices types
> lede-17.01: batman-adv: Merge bugfixes from 2018.0

- bmx7/Makefile
Sysupgrade currently leads to a loss of the content of /etc/bmx7 which contains the secret keys.
After the reboot the device creates new IPs leading to a new "identity" aka ID, shortID and IPv6 changes.
> bmx7: keep bmx7 secret keys on sysupgrade

- bmx7/files/etc/init.d/bmx7
Using procd allows better control and monitoring of the bmx7 process.
Keep polling for mac80211.sh process for now until we find a better
way to make sure that wireless configuration has been generated before
starting bmx7.
Setting maximum core size to 20000 looks dangerous on small devices,
but keep it as it was before, we shall discuss this separately.
> bmx7: convert init script to use procd

- alfred/files/alfred.init
Occationally /proc/net/if_inet6 contains interface IDs with
three digits. In this case, the regex in wait_for_ll_address()
does not work anymore and alfred is not starting.
> alfred: Support interface IDs with more than two digits

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
batman-adv 2018.1
=================
* support latest kernels (3.2 - 4.17)
* add DAT cache and multicast flags netlink support
* avoid redundant multicast TT entries
- update data pointers after skb_cow()
- fix header size check in batadv_dbg_arp()
- fix skbuff rcsum on packet reroute
- fix multicast-via-unicast transmission with AP isolation
- fix packet loss for broadcasted DHCP packets to a server
- fix multicast packet loss with a single WANT_ALL_IPV4/6 flag
batctl 2018.1
=============
* synchronization of batman-adv netlink and packet headers
* add DAT cache and multicast flags netlink support
* disable translation support for non-unicast mac addresses
alfred 2018.1
=============
* synchronization of batman-adv …
> batman-adv 2018.1

- smcroute/Makefile
FTP is a lot more unreliable than HTTP(S). uscan was recently having trouble.
Signed-off-by: Rosen Penev <rosenp@gmail.com
> smcroute: Change download to HTTP

- nodogsplash2/Makefile
- nodogsplash2/files/nodogsplash.config
- nodogsplash2/files/nodogsplash.init
nodogsplash2: Add NDS Restart Hook for Firewall
NodogSplash iptables entries are overwritten if the OpenWrt Firewall is restarted.
This change adds an include hook to /etc/config/firewall to restart NodogSplash if Firewall is restarted.
Author-name: Rob White
Signed-off-by: Rob White rob@blue-wave.net
> nodogsplash2: Add NDS Restart Hook for Firewall

- babeld/Makefile
This fixes a serious bug where IPv4 routes were not being redistributed.
Signed-off-by: Baptiste Jonglez <git@bitsofnetworks.org>
> babeld: Update to 1.8.2

- pimbd/Makefile
Maintainer: @Oryon 
Compile tested: brcm47xx/ramips, mipsel, openwrt master
When compiling with gcc 7.3.0, we get this error:
```
pimbd-2015-08-18-68f5fc803119e4b33a88b35c096f4d6ac28b6de5/src/mrib.c:57:34:
error: braced-group within expression allowed only inside a function
static uint32_t ipv4_rtr_alert = cpu_to_be32(0x94040000);
```
gcc 7.3.0 thinks that `cpu_to_be32()` is not a compile-time constant, so
it does not allow it to initialize `ipv4_rtr_alert` outside of a function.
We need to use `__constant_cpu_to_be32()` instead.
I've submitted this upstream as well: https://github.com/Oryon/pimbd/pull/3
(hopefully this won't count as a duplicate)
Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>
> pimbd: Fix gcc 7.3 compilation error

- bird2/Makefile
Explicitly disable libssh support
Fixes build failure on buildbots
" Package bird2 is missing dependencies for the following libraries:
libssh.so.4 "
http://downloads.lede-project.org/snapshots/faillogs/arm_cortex-a9_neon/routing/bird2/compile.txt
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>
> bird2: Disable libssh support

- nodogsplash2/files/etc/init.d/nodogsplash
Remove reference to dead code that prevents startup.
Tested with openwrt master on a wt3020.
> nodogsplash2: remove reference to dead code

- ndppd/patches/0001-Version-bump.patch
- ndppd/patches/0002-Fixes-strerror_r-GNU-XSI.patch
- ndppd/patches/0003-fix-poll-header.patch
Error:
src/logger.cc: In static member function 'static std::string ndppd::logger::err()':
src/logger.cc:86:22: error: could not convert 'strerror_r((*__errno_location()), ((char*)(& buf)), sizeof (buf))'
from 'int' to 'std::string {aka std::basic_string<char>}'
return strerror_r(errno, buf, sizeof(buf));
Added and modified some patches from
https://github.com/DanielAdolfsson/ndppd/compare/eb81b8f2d6d4d33545570402b049a73880b9ad01...navossoc:master
(See https://github.com/DanielAdolfsson/ndppd/issues/40 for details)
Maintainer: @kerneis 
Compile-tested: octeon + mpc85xx openwrt master, musl + uclibc++
octeon openwrt master, glibc + libstdc++
Run-tested: octeon openwrt master, musl + uclibc++
Signed-off-by: Martin Strobel <arctus@crza.de>
> ndppd: fix compile error with musl

- nodogsplash/Makefile
- nodogsplash/files/etc/uci-defaults/40_nodogsplash
Fixes a heredoc block and add nodogsplash2 as a conflicting package.
> nodogsplash: fix minor things

- nodogsplash/Makefile
- nodogsplash/files/etc/config/nodogsplash
- nodogsplash/files/etc/init.d/nodogsplash
This release adds fully integrated support for a separate Forwarding Authentication Service (FAS) with the option of using Binauth as a post authentication processor. In addition an enhancement to ndsctl allows individual client information to be easily obtained. This ndsctl enhancement is intended for use by both FAS and Binauth for various potential applications but specifically to facilitate a secure FAS.
> nodogsplash: Release 3.1.0

- nodogsplash/Makefile
This release introduces the following enhancments:
*  Add Redirect to Status page support for FAS [bluewavenet]
*  Add iptables version check [mwarning]
*  Add ndsctl status output for FAS and Binauth status. [bluewavenet]
*  Initialize fas_remoteip with gw_address and simplify code [mwarning]
*  Fix Readthedocs updates and update Docs URL [bluewavenet]
*  Update documentation and Debian man page [bluewavenet]
> nodogsplash: Release 3.2.0

- nodogsplash/Makefile
- nodogsplash/files/etc/config/nodogsplash
- nodogsplash/files/etc/init.d/nodogsplash
sessiontimeout (minutes) until client is forced out
checkinterval (seconds) interval at which nodogsplash checks client timeout status
Add real world useful values to timeout options.
Signed-off-by: Rob White rob@blue-wave.net
> nodogsplash: add missing config options

- nodogsplash/Makefile
Bugfixes and minor enhancements:
* reset upload/download counter when a client has been authenticated a second time [mwarning]
* print sesssion duration as 0 in "ndsctl json" and "ndsctl clients" output when a session has not been started [mwarning]
* rework html templater to speed up splash page generation [mwarning]
* FAS documentation updates [bluewavenet]
* Add CSS file and update splash and status html [bluewavenet]
> nodogsplash: Version 3.2.1 release

- nodogsplash/Makefile
This release provides bugfixes and some minor enhancements:
* reset upload/download counter when a client has been authenticated a second time [mwarning]
* print sesssion duration as 0 in "ndsctl json" and "ndsctl clients" output when a session has not been started [mwarning]
* rework html templater to speed up splash page generation [mwarning]
* FAS documentation updates [bluewavenet]
* Add CSS file and update splash and status html [bluewavenet]
> nodogsplash: Backport v3.2.1 to OpenWrt 18.06

- nodogsplash/Makefile
The tagging of the release was wrong, as a result, the hash is different from the usual package tar.gz.
The content has been verified to be the same.
> nodogsplash: fix download link

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
@simonwunderlich  These are various fixes for the batman-adv related packages. But there are two main changes:
The Module.symvers with the exported symbols of all other kernel modules in OpenWrt is usually placed in the main source directory of the package. But the actual sources for batman-adv are found in net/batman-adv. OpenWrt must therefore be informed to move it to this subdirectory or otherwise modpost will fail to find the symbols
WARNING: "cfg80211_get_station" [.../batman-adv-2018.3/net/batman-adv/batman-adv.ko] undefined!
The dependency will then be missing in the .modinfo depends= option and thus it the kernel module loader will not correctly load the cfg80211.ko during bootup.
----
Add openwrt revision to internal version
OpenWrt is using a modified version of the software …
> batman-adv package fixes

- batman-adv/Config.in
- batman-adv/Makefile
The kernel already provides all available kernel options for batman-adv and even includes more verbose descriptions of each option. Importing this Kconfig (with minor adjustments) file as Config.in allows to share most information between kernel and OpenWrt.
> batman-adv: Cleanup of configuration options

- luci-app-bmx7/files/www/cgi-bin/bmx7-info
Tested on OpenWrt SNAPSHOT, r8651-ffa5538 and BMX7 version=BMX7-0.2 compatibility=21 revision=9883383 id=EE598CB557DF0E80988F2450DCE43F8E6064F112875D363C5839309A nodeKey=RSA2048 linkKeys=RSA896,DH2048M112 descSqn=215 ip=fd70:ee59:8cb5:57df:e80:988f:2450:dce4 hostname=OpenWrt
> Fix bmx7-info indentation and "$info" call

- luci-app-bmx6/bmx6/www/luci-static/resources/bmx6/js/bmx6-graph.js
The JavaScript code of the network graph tried to fetch the topology from
%HOST/cgi-bin/luci/status/bmx6/topology, but the topology entry is now located
at admin->network->BMX6 (i.e., %HOST/cgi-bin/luci/admin/network/BMX6/topology).
Fixes #432
Signed-off-by: Roger Pueyo Centelles <roger.pueyo@guifi.net>
> luci-app-bmx6: Fix URL of network topology JSON file

- luci-app-bmx6/bmx6/usr/lib/lua/luci/model/bmx6json.lua
This commit adds a dirty fix to issue https://github.com/openwrt-routing/packages/issues/436. Just adding the sys.exec("") call makes the topology and the graph be shown properly, not even a sleep command is needed.
Ideally, the wget() function should be reviewed by any of the contributors (@nicopace, @p4u) to properly identify where the problem is and fix it.
Signed-off-by: Roger Pueyo Centelles <roger.pueyo@guifi.net>
> luci-app-bmx6: Avoid race condition in bmx6json.lua get()

- nodogsplash/Makefile
Due to rearrangements of the libmicrohttpd the non
ssl variant is now called libmicrohttpd.
Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>
> nodogsplash: libmicrohttpd-no-ssl -> libmicrohttpd

- batctl/Makefile
* correct binary for batctl-default to /usr/libexec/batctl-default; it was ```/usr/sbin/batctl -> /usr/libexec/batctl-full```
* while at it fix description of batctl-full
> batctl: fix wrong binary-name for batctl-default

- nodogsplash/Makefile
- nodogsplash/patches/0001-fix-invalid-pointer-when-clock-is-turned-back.patch
Fixes a invalid pointer error when the clock is set into the past while nodogsplash is running.
Tested with current OpenWrt master and Nexx wt3020.
> nodogsplash: fix invalid pointer bug when clock is turned back

- batman-adv/Makefile
- batman-adv/files/etc/uci-defaults/99-migrate-batadv_hardif
Although batman-adv config is cycled in config_foreach, changes
are made in the network config. Thus, this one has to be committed.
Signed-off-by: Adrian Schmutzler <freifunk@adrianschmutzler.de>
> batman-adv: Fix uci commit target

- nodogsplash/Makefile
Add missing install directories in revised Makefile
Signed-off-by: Rob White rob@blue-wave.net
> nodogsplash: Add missing install directories

- nodogsplash/Makefile
Compiled and tested on snapshot SDK mips_24kc and arm_cortex-a5_neon-vfpv4/
* Fix Issue introduced in v3.3.0 with the addition of Improvements towards usable IPv6 support, that caused CPD on client devices to fail with "Too Many Redirects" error. NDS now terminates gracefully with a console error if fasremoteip is not set AND fasport=80  [bluewavenet]
* Validate fasremoteip to ensure that if it is set, then it is a valid dotted format IPv4 address  [bluewavenet]
* Numerous Documentation updates  [bluewavenet]
* Fix to Known Issue on OpenWrt >18.x.x with v3.3.1. This was caused by misconfigured Makefile for libmicrohttpd; this has been fixed there [bluewavenet]
Signed-off-by: Rob White `<rob@blue-wave.net>`
> nodogsplash: Release v3.3.2-1

- bird1/Makefile
Maintainer: @Noltari (cc @tohojo )
Compiled tested: cortexa53, Turris MOX, OpenWrt master
Description:
- version bump
- changed PKG_MD5SUM to PKG_HASH
- bird website use HSTS, so let's use HTTPS
> bird1: update to version 1.6.6

- bird/Makefile
Maintainer: @Noltari 
Compile tested: cortexa53, Turris MOX, OpenWrt 18.06.02
Description: update to version 1.6.6 and use HTTPS instead of HTTP
> [OpenWrt 18.06] bird: update to version 1.6.6

- nodogsplash/Makefile
Compiled and tested on snapshot SDK mips_24kc and arm_cortex-a5_neon-vfpv4/
* Introduce aes encryption of the query string passed to remote FAS, allowing authdir and client token to be transferred securely. Uses php-cli and php-openssl. These are required if encryption is enabled but are not dependencies [bluewavenet]
* Introduce fasremotefqdn, specifying the FQDN of the remote FAS. This facilitates simplified support for FAS operation on shared hosting systems [bluewavenet]
* Add a FAS php script supporting aes encrypted query string sent from NDS [bluewavenet]
* Numerous Documentation updates [bluewavenet]
* Remove unused pagesdir and imagesdir [mwarning]
* Add Preauth script that displays images from remote servers [bluewavenet]
* Use …
> nodogsplash: Release 4.0.0

- cjdns/Makefile
Not supported.
https://downloads.openwrt.org/snapshots/faillogs/arc_archs/routing/cjdns/compile.txt
> cjdns-tests: Don't build on ARC

- nodogsplash/Makefile
This version has numerous fixes and enhancements.
It is compatible with the previous v3.2.1 release and onwards.
Important fixes in this version:
* Fix coding error in fas-aes.php [bluewavenet]
* Make debuglevel platform independent [mwarning]
* Fix memory handling bug, issue nodogsplash/nodogsplash#341 [mwarning] [stevo01]
* ndsctl_thread - ignore interupts when returning from epoll [lynxis]
* auth.c - use correct types to prevent cast and comparement of uint and int [lynxis]
* openwrt/init.d - prevent start of the daemon if configuration generation fails [lynxis]
* Generate Error 403 Forbidden, if Gateway Port is accessed directly [bluewavenet]
* Validate fasremoteip as a valid dotted format IPv4 address [bluewavenet] [mwarning]
* Prevent client CPD "Too Many Redirects" error. …
> nodogsplash: Backport Version 4.0.1.

- nodogsplash/Makefile
nodogsplash: Release 4.0.1
This release has numerous updates, fixes and documentation improvements.
Maintainer: Moritz Warning <moritzwarning@web.de>
Compiled and tested on snapshot SDK mips_24kc
From the changelog:
* Make debuglevel platform independent [mwarning]
* Add/move/reword some debug output lines [mwarning]
* Numerous code cleanups [mwarning]
* Put fas code into block [mwarning]
* Fix coding error in fas-aes.php incorrectly passing redir back to NDS [bluewavenet]
* Numerous documentation updates [bluewavenet]
Signed-off-by: Rob White `<rob@blue-wave.net>`
> nodogsplash: Release 4.0.1

- batman-adv/patches/0001-Revert-batman-adv-convert-stream-like-files-from-non.patch
- batman-adv/patches/0002-Revert-batman-adv-compat-Drop-support-for-genl_ops-s.patch
- batman-adv/patches/0003-Revert-batman-adv-genetlink-optionally-validate-stri.patch
- batman-adv/patches/0004-Revert-batman-adv-genetlink-make-policy-common-to-fa.patch
----
The patches were accidentally deleted while testing the batman-adv 2019.3 bugfixes with various OpenWrt versions. But OpenWrt 19.07 will be released with a mac80211 package which still uses the Linux 4.19 API. And thus the OpenWrt 19.07 openwrt-routing branch still has to retain these compat patches.
Fixes: a93e68447a55 ("alfred: Merge bugfixes from 2019.3")
> batman-adv: Readd Linux 4.19.x compat patches

- nodogsplash/Makefile
Compiled and tested on snapshot SDK mips_24kc
This release has numerous bug fixes and enhancements:
* Fix bug - fas_remotefqdn not supported with option fas_secure_enabled 0 [bluewavenet]
* Fix bug - prevent deadlock causing ndsctl to hang and NDS to become unresponsive [bluewavenet]
* PreAuth - Override FAS settings making configuration foolproof [bluewavenet]
* ndsctl - make json parsing consistent for all client variables [bluewavenet]
* Fix memory leak in template generation [lynxis]
* When executing the ndsctl stop command, cleanup all structures [lynxis]
* Check for positive errno in thread_ndsctl [lynxis]
Signed-off-by: Rob White `<rob@blue-wave.net>`
> nodogsplash: Release 4.0.2

- bird1/Makefile
- bird2/Makefile
Upstream released new versions of both series of the Bird routing daemon on August 5th. Bump the package Makefiles.
Compile tested on OpenWrt 18.06 for ar71xx.
> Bird: Bump package versions to 1.6.7 and 2.0.5

- bmx7/Makefile
The extra MAKE_ARGS were no longer taken into account resulting in
erros. Also more path fixes and some longline splitting.
Signed-off-by: Paul Spooren <mail@aparcar.org>
> bmx7: fixup Makefile

- nodogsplash/Makefile
nodogsplash: Release 4.2.0
Compiled and tested on snapshot SDK mips_24kc and arm_cortex-a7_neon-vfpv4
This release adds significant functionality in the form of capturing the client User-Agent string and passing to both PreAuth and BinAuth scripts. Compatibility is maintained with previous versions.
Changelog since last OpenWrt release:
* BinAuth - Send User Agent string and client-ip to the binauth script [bluewavenet]
* BinAuth - Update the two example BinAuth scripts showing use of passed arguments [bluewavenet]
* Documentation - Update BinAuth section [bluewavenet]
* PreAuth - Send User Agent string to the preauth script [bluewavenet]
* PreAuth - Update the example PreAuth script showing use of passed arguments [bluewavenet]
* …
> nodogsplash: Release 4.2.0

- nodogsplash/Makefile
nodogsplash: Version 4.3.0
Compiled and tested on snapshot SDK mips_24kc and arm_cortex-a7_neon-vfpv4
This release has major new functionality in the form of token hashing, (extension to fas_secure level-1) mitigating the problems with remote FAS where access to the local ndsctl would be otherwise required.
Although not as flexible as level 2, this extension has much smaller memory and storage requirements so is ideal for implementation on legacy hardware.
There are also numerous enhancements, updates and fixes.
All changes are compatible with the previous release.
Latest changelog:
* Create switch option to select preinstalled templated splash or preauth login [bluewavenet]
* Limit PreAuth and BinAuth log size in example scripts …
> nodogsplash: Version 4.3.0

- bird1/Makefile
- bird2/Makefile
Maintainer: @Noltari and @tohojo 
Compile tested: mvebu, Turris Omnia, OpenWrt master.
Changelog:
[Version 2.0.6 (2019-09-10)](https://gitlab.labs.nic.cz/labs/bird/blob/v2.0.6/NEWS)
o RAdv: Solicited unicast RAs
o BGP: Optional Adj-RIB-Out
o BGP: Extended optional parameters length
o Filter: Sets and set expressions in path masks
o Several important bugfixes
[Version 1.6.8 (2019-09-10)](https://gitlab.labs.nic.cz/labs/bird/blob/v1.6.8/NEWS)
o Several important bugfixes
> bird{1,2}: Update to version 1.6.8 and 2.0.6

- nodogsplash/Makefile
nodogsplash: Version 4.3.3 release
Compiled and tested on snapshot SDK mips_24kc and arm_cortex-a7_neon-vfpv4
This version fixes two issues that can cause NDS to lock or crash, one, a coding error that leads to memory corruption and two, deadlocks in iptables and ndsctl. Both of these issues occur at high loads and/or at high CPD detection rates.
In addition, in some circumstances, a deauthenticated client running a vpn may have suffered from querystring truncation causing vpn failure.
Some minor updates are also included.
Extract from changelog:
* Fix Memory corruption at high loads [bluewavenet]
* Prevent iptables and ndsctl deadlocks [lynxis]
* Prevent query string truncation for deauthenticated client when client is using some types …
> nodogsplash: Version 4.3.3 release

- batman-adv/patches/0007-batman-adv-fix-uninit-value-in-batadv_netlink_get_if.patch
- batman-adv/patches/0008-batman-adv-Only-read-OGM-tvlv_len-after-buffer-len-c.patch
- batman-adv/patches/0009-batman-adv-Only-read-OGM2-tvlv_len-after-buffer-len-.patch
- batman-adv/patches/0010-batman-adv-Avoid-free-alloc-race-when-handling-OGM2-.patch
- batman-adv/patches/0011-batman-adv-Avoid-free-alloc-race-when-handling-OGM-b.patch
- batman-adv/patches/0012-batman-adv-Introduce-own-OGM2-buffer-mutex.patch
- batman-adv/patches/0013-batman-adv-Avoid-OGM-workqueue-synchronous-cancel-de.patch
----
batman-adv
==========
* fix uninit-value in batadv_netlink_get_ifindex()
* Only read OGM tvlv_len after buffer len check
* Only read OGM2 tvlv_len after buffer len check
* Avoid free/alloc race when handling OGM2 buffer
* Avoid free/alloc race when handling OGM buffer
* Introduce own OGM2 buffer mutex
* Avoid OGM workqueue synchronous cancel deadlock
> openwrt-19.07: batman-adv: Merge bugfixes from 2019.4

- batman-adv/patches/0010-batman-adv-fix-uninit-value-in-batadv_netlink_get_if.patch
- batman-adv/patches/0011-batman-adv-Only-read-OGM-tvlv_len-after-buffer-len-c.patch
- batman-adv/patches/0012-batman-adv-Only-read-OGM2-tvlv_len-after-buffer-len-.patch
- batman-adv/patches/0013-batman-adv-Avoid-free-alloc-race-when-handling-OGM2-.patch
- batman-adv/patches/0014-batman-adv-Avoid-free-alloc-race-when-handling-OGM-b.patch
- batman-adv/patches/0015-batman-adv-Introduce-own-OGM2-buffer-mutex.patch
- batman-adv/patches/0016-batman-adv-Avoid-OGM-workqueue-synchronous-cancel-de.patch
----
batman-adv
==========
* fix uninit-value in batadv_netlink_get_ifindex()
* Only read OGM tvlv_len after buffer len check
* Only read OGM2 tvlv_len after buffer len check
* Avoid free/alloc race when handling OGM2 buffer
* Avoid free/alloc race when handling OGM buffer
* Introduce own OGM2 buffer mutex
* Avoid OGM workqueue synchronous cancel deadlock
> openwrt-18.06: batman-adv: Merge bugfixes from 2019.4

- batman-adv/patches/0010-batman-adv-fix-uninit-value-in-batadv_netlink_get_if.patch
- batman-adv/patches/0011-batman-adv-Only-read-OGM-tvlv_len-after-buffer-len-c.patch
- batman-adv/patches/0012-batman-adv-Only-read-OGM2-tvlv_len-after-buffer-len-.patch
- batman-adv/patches/0013-batman-adv-Avoid-free-alloc-race-when-handling-OGM2-.patch
- batman-adv/patches/0014-batman-adv-Avoid-free-alloc-race-when-handling-OGM-b.patch
- batman-adv/patches/0015-batman-adv-Introduce-own-OGM2-buffer-mutex.patch
- batman-adv/patches/0016-batman-adv-Avoid-OGM-workqueue-synchronous-cancel-de.patch
----
batman-adv
==========
* fix uninit-value in batadv_netlink_get_ifindex()
* Only read OGM tvlv_len after buffer len check
* Only read OGM2 tvlv_len after buffer len check
* Avoid free/alloc race when handling OGM2 buffer
* Avoid free/alloc race when handling OGM buffer
* Introduce own OGM2 buffer mutex
* Avoid OGM workqueue synchronous cancel deadlock
> lede-17.01: batman-adv: Merge bugfixes from 2019.4

- cjdns/Makefile
- luci-app-cjdns/Makefile
> Changes like correcting md5sums, changing mirror URLs, adding a maintainer field or updating a comment or copyright year in a Makefile do not require a change to PKG_RELEASE
> maintainer change see #398
> cjdns: luci-app-cjdns: update maintainer

- luci-app-cjdns/Makefile
After https://github.com/openwrt/luci/commit/284918bfaf2f6d7e46fb11377bb9a537b35dd58a commit in openwrt/luci, every app which uses cbi requires luci-compat package.
> luci-app-cjdns: Add luci-compat requirement

- pimbd/Makefile
Maintainer: @Oryon
Compile tested: Turris Omnia, mvebu, OpenWrt 18.06.
Fixes: #527 by cherry-picking #392.
> [OpenWrt 18.06] pimbd: Update to 2018-06-19

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
This changes the package version string so it does not start
with "openwrt", but with the base version we are modifying:
So far: openwrt-2019.4-1
Now:    2019.4-openwrt-1
Since it's us modifying version 2019.4 (in this case), this order
is more convenient (and also closer to what the kernel version
string does).
> batman-adv and friends: improve version string

- bird2/Makefile
Bump release to upstream v2.0.7
Signed-off-by: Toke Høiland-Jørgensen <toke@toke.dk>
> bird2: Update to v2.0.7

- bird/Makefile
Maintainer: @Noltari and @tohojo
Compile tested: Turris 1.1, powerpc p2020, OpenWrt 18.06.05
Version 1.6.7:
o BFD: Support for VRFs
o Several bugfixes
Version 1.6.8:
Fixes [CVE-2019-16159](https://nvd.nist.gov/vuln/detail/CVE-2019-16159) and includes important bugfixes
> [OpenWrt 18.06] bird: Update to version 1.6.8 (security fix)

- nodogsplash/Makefile
Maintainer: Moritz Warning <moritzwarning@web.de>
Compiled and tested on snapshot SDK mips_24kc and arm_cortex-a7_neon-vfpv4
This release adds significant new functionality yet is compatible with the previous version.
From the changelog:
* Add Client Network Zone detection supporting local interfaces and 802.11s mesh [bluewavenet]
* Add client zone and user agent to FAS/PreAuth logs [bluewavenet]
* Add requirements for retrieving https remote image for login page [bluewavenet]
* Add htmlentity encode and decode to preauth scripts [bluewavenet]
* Implement unescape callback for MHD allowing url special characters to be used in login forms [bluewavenet]
* Create get_client_interface library utility [bluewavenet]
* Create unescape library utility [bluewavenet]
* Update demo-preauth, …
> nodogsplash: Version 4.4.0 release

- ahcpd/Makefile
PKG_MD5SUM is deprecated and does not accurately represent the SHA256 hash.
> ahcpd: Replace PKG_MD5SUM with PKG_HASH

- ahcpd/Makefile
- The old page redirects to a new one and it uses HTTPS.
Let's skip that redirect in PKG_SOURCE_URL and URL.
- Reorder some things to be sync with Makefiles in packages feed
- Add PKG_LICENSE_FILES
Fixes: 47edf2d27594083f91777913bbe57c43a2927f09 (ahcpd: Replace
PKG_MD5SUM with PKG_HASH)
Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>
> ahcpd: use SHA256 hash and use HTTPS everywhere

- quagga/Makefile
- quagga/patches/001-bgpd-Fix-AS_PATH-size-calculation-for-long-paths.patch
- quagga/patches/002-Quagga-2018-0543.patch
- quagga/patches/003-Quagga-2018-1114.patch
- quagga/patches/004-Quagga-2018-1550.patch
- quagga/patches/005-Quagga-2018-1975.patch
- quagga/patches/150-no-cross-fs-link.patch
Maintainer: @acinonyx 
Compile and run tested: Turris Omnia, mvebu, OpenWrt 18.06.
Makefile changes:
- Use HTTPS everywhere
- Reorder some things to have it in sync with other packages
- Fixed SPDX License Identifier
- Added PKG_LICENSE_FILES
- For checksum use SHA256
Refreshed patches
Fixes CVEs:
- [CVE-2017-5495](https://nvd.nist.gov/vuln/detail/CVE-2017-5495)
- [CVE-2017-16227](https://nvd.nist.gov/vuln/detail/CVE-2017-16227)
Fixes security issues:
- [Quagga-2018-0543](https://gogs.quagga.net/Quagga/quagga/src/master/doc/security/Quagga-2018-0543.txt): attr_endp used for NOTIFY data
- [Quagga-2018-1114](https://gogs.quagga.net/Quagga/quagga/src/master/doc/security/Quagga-2018-1114.txt): bgpd double free
- [Quagga-2018-1550](https://gogs.quagga.net/Quagga/quagga/src/master/doc/security/Q …
> [OpenWrt 18.06] quagga: update to version 1.1.1

- bird2/Makefile
- bird2/files/bird.init
`/etc/init.d/bird restart` or `/etc/init.d/bird reload` has no effects.
This PR fixes this issue by:
- running the service in the foreground to meet the requirements of procd
- sending SIGHUP signal to reload the service
> bird2: fix service restart and reload

- luci-app-bmx6/Makefile
- luci-app-bmx6/bmx6/usr/lib/lua/luci/view/bmx6/nodes_j.htm
- luci-app-bmx6/bmx6/usr/lib/lua/luci/view/bmx6/status_j.htm
- luci-app-bmx6/bmx6/usr/lib/lua/luci/view/bmx6/tunnels_j.htm
- affected three tab luci templates (even with luci-compat installed)
- fixes #548
- as jow said in #548:
- it might be that modern LuCI escapes it as %24 while old versions passed it
on as-is
- bmx6-info removes it anyway
https://github.com/openwrt-routing/packages/blob/master/luci-app-bmx6/bmx6/www/cgi-bin/bmx6-info#L22
you can probably just remove it in all three tab templates
> luci-app-bmx6: bugfix format to query bmx6-info

- bird2/Makefile
- bird2/files/bird.init
Compile tested: Turris 1.1, powerpc 8540, OpenWrt 19.07.
Fixes #557
> [19.07] bird2: backport from master update to version 2.0.7 + fix restart&reload

- opennds/Makefile
Maintainer: Rob White `<rob@blue-wave.net>`
Compiled and tested on snapshot SDK for mipsel_24kc, mips_24kc and arm_cortex-a7_neon-vfpv4
This is the first release from the OpenNDS project.
The decision has been made by the developers of the NoDogSplash project, to create a new project, beginning at v5.0.0
The two resulting projects are:
* **OpenNDS**, the new project, optimised for development of custom captive portal solutions using the built in Forwarding authentication Services API and associated libraries.
* **NoDogSplash**, the original project, optimised for hardware with very restricted resources (eg legacy 8/32 devices) and supporting only simple templated splash pages.
At v5.0.0 of both projects share a common code base.
However, the two packages will inevitably and rapidly …
> opennds: Create new Package, release v5.0.0

- babeld/Makefile
21 April 2020: babeld-1.9.2
* Fixed two issues that could cause IPv4 routes to be represented
incorrectly, with a range of confusing symptoms.  Thanks to
Fabian Bläse.
* Fixed incorrect parsing of TLVs with an unknown Address Encoding.
Thanks to Théophile Bastian.
* Fixed access to mis-aligned data structure.  Thanks to Antonin Décimo.
Signed-off-by: Fabian Bläse <fabian@blaese.de>
> babeld: Update to version 1.9.2

- babeld/Makefile
21 April 2020: babeld-1.9.2
* Fixed two issues that could cause IPv4 routes to be represented
incorrectly, with a range of confusing symptoms.  Thanks to
Fabian Bläse.
* Fixed incorrect parsing of TLVs with an unknown Address Encoding.
Thanks to Théophile Bastian.
* Fixed access to mis-aligned data structure.  Thanks to Antonin Décimo.
Signed-off-by: Fabian Bläse <fabian@blaese.de>
> [19.07] babeld: Update to version 1.9.2

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
----
batman-adv 2020.1
=================
* support latest kernels (3.16 - 5.7)
* fix reference leaks in throughput_override sysfs file
* fix reference leak in B.A.T.M.A.N. V OGM error handling
* fix network coding random weighting
batctl 2020.1
=============
* Fix error code on throughputmeter errors
> batman-adv 2020.1

- nodogsplash2/Makefile
> nodogsplash2: update to 2.1.2

- nodogsplash/Makefile
Fix a traversal path attack.
Signed-off-by: Alexander Couzens <lynxis@fe80.eu>
> nodogsplash: update to 4.0.3

- opennds/Makefile
Maintainer: Rob White <rob@blue-wave.net>
Compiled and tested on snapshot SDK for mipsel_24kc, mips_24kc and arm_cortex-a7_neon-vfpv4
This release provides a fix for a Path Traversal Attack vulnerability present in libmicrohttpd's built in unescape functionality.
> opennds: Release v5.0.1

- batman-adv/Makefile
It is easier to use the global define than to manually keep track of the changes in the various kernel module makefiles in the main OpenWrt repository and feeds. One effect should be that the absolute build_dir information is no longer included in the batman-adv.ko
Also the mac80211's autoconf.h is included to avoid ABI incompatibilities between mac80211 and batman-adv.
> batman-adv: use KERNEL_MAKE_FLAGS for kernel module compilation

- opennds/Makefile
Maintainer: Rob White <rob@blue-wave.net>
Compiled and tested using snapshot SDK for mipsel_24kc, mips_24kc and arm_cortex-a7_neon-vfpv4
OpenNDS v5.1.0 release
This release adds major functionality and provides numerous fixes:
Data Rate and Data Volume Quotas are implemented.
BinAuth / fas_secure_enabled level 3 compatibility is implemented.
Page fault and crash when ndsctl auth is called and client not found has been fixed.
From the ChangeLog:
* Add - Generic Linux - install opennds.service [bluewavenet]
* Add - Documentation updates [bluewavenet]
* Add - config file updates [bluewavenet]
* Add - Install sitewide username/password splash support files [bluewavenet]
* Add - quotas to binauth_sitewide [bluewavenet]
* Add - Splash page updates [bluewavenet]
* Add - Implement Rate Quotas …
> opennds: Release v5.1.0

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
----
batman-adv 2020.2
=================
* support latest kernels (4.4 - 5.8)
* dropped support for kernels < 4.4
* re-enabled link speed detection for interfaces without auto negotiation
batctl 2020.2
=============
* drop support for automatic destruction of empty meshifs
* Fix parsing of radiotap headers on big endian systems
alfred 2020.2
=============
* Rephrase names of server roles
> batman-adv 2020.2

- opennds/Makefile
* This version - for Openwrt **after** 19.07 - for compatibility with new MHD API
* Set - minimum version of MHD to 0.9.71 for new MHD API [bluewavenet]
* Set - use_outdated_mhd to 0 (disabled) as default [bluewavenet]
* Add - Multifield PreAuth login script with css update [bluewavenet]
* Add - Documentation and config option descriptions for configuring Walled Garden IP Sets
> opennds: Release v6.0.0

- opennds/Makefile
opennds: Backport v5.2.0
Designed to replace the old NoDogsplash v4.0.3 package.
NoDogSplash v4.0.3 still contains the FAS API but has numerous bugs,
some serious, but is no longer supported as the decision was made to
split into two projects - openNDS with FAS and NoDogSplash optimised for
devices with minimal resources.
This version of openNDS is functionally the same as v6.0.0, but supports
libmicrohttpd (MHD) versions up to 0.9.70 that use the old MHD API.
There are many additions and bugfixes over NoDogSplash v4.0.3.
eg 
Bugfix:
* Page fault when ndsctl auth is called and client not found
* Missing NULL parameter in MHD_OPTION_UNESCAPE_CALLBACK causing page fault
Functionality:
* HTTPS remote FAS
* Upload/Download Quotas
From the Changelog:
openNDS (5.2.0)
* This version - for …
> openwrt-19.07: opennds: Backport v5.2.0

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/files/lib/netifd/proto/batadv_hardif.sh
---
batman-adv
==========
* support latest kernels (4.4 - 5.9)
* introduce a configurable per interface hop penalty
* avoid uninitialized chaddr when handling DHCP
* fix own OGMv2 check in aggregation receive handling
* fix "NOHZ: local_softirq_pending 08" warnings caused by BLA
batctl
====
* add per interface hop penalty command
alfred
====
* synchronization of batman-adv netlink header
> batman-adv: upgrade package to latest release 2020.3

- batctl/Makefile
The mcast_flags subcommand allows to query the mcast_flags of the current device and of the seen originators. It should be enabled for the default and full variants. But the configuration string wasn't correctly included in the list when the variants were prepared and thus disabled in all variants.
Reported-by: Linus Lüssing <linus.luessing@c0d3.blue>
Fixes: 129986825219 ("batctl: Provide different variants")
----
> batctl: Enable build of mcast_flags subcommand

- olsrd/Makefile
- olsrd/patches/011-bison.patch
With the upgrade to bison 3.7.1 (openwrt commit 1cf842d) building
olsrd was failing.  Now, instead of the contents of header files
being directly inserted into the generated source files, they are
instead included with a #include directive.
The local.mk has, until now, done some magic with *-tmp files,
which is not longer necessary and even causes builds to fail.
src/cfgparser/oparse.c:265:10: fatal error: oparse.h-tmp: No such file or directory
#include "oparse.h-tmp"
Suggested-by: Jo-Philipp Wich <jo@mein.io>
Signed-off-by: Perry Melange <isprotejesvalkata@gmail.com>
> olsrd: migrate to using bison 3.7.1

- oonf-dlep-proxy/patches/010-gcc10.patch
> oonf-dlep-proxy: fix compilation with GCC 10

- olsrd/patches/012-gpsd.patch
As mentioned in gpsd.h:
"Move gps_data_t->status to gps_fix_t.status for better fix merging"
> olsrd: adapt gpsdclient.c to new gpsd lib

- oonf-olsrd2/patches/020-static.patch
The GCC 10 patch marked several variables in headers as extern, which
is correct. However some upstream change marked the definitions as
static even though the definition was not local to the c files.
> oonf-olsrd2: fix static problems

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/patches/0001-Revert-batman-adv-genetlink-move-to-smaller-ops-wher.patch
- batman-adv/src/compat-hacks.h
---
batman-adv
==========
* support latest kernels (4.4 - 5.10)
* fix incorrect reroute handling of multicast packets
* improve handling of multicast packets by bridge loop avoidance
batctl
====
* Fix endianness in ICMPv6 Echo Request/Reply parsing
> batman-adv: upgrade package to latest release 2020.4

- batman-adv/patches/0052-batman-adv-mcast-fix-duplicate-mcast-packets-in-BLA-.patch
The build can fail in some configurations because the include for batadv_send_skb_unicast was missing in batman-adv 2018.1.
Reported-by: Martin Weinelt <martin@darmstadt.freifunk.net>
Fixes: c197ddb22531 ("batman-adv: Merge bugfixes from 2020.4")
> batman-adv: Fix missing include for backported 2020.4 patch

- opennds/Makefile
This version introduces major new enhancements and the disabling or removal of deprecated functionality.
* Add - built in autonomous Walled Garden operation [bluewavenet]
* Add - Support for Custom Parameters [bluewavenet]
* Add - Quota and rate reporting to ndsctl json. Format output and fix json syntax errors [bluewavenet]
* Add - global quotas to output of ndsctl status [bluewavenet]
* Add - Report Rate Check Window in ndsctl status and show client quotas [bluewavenet]
* Add - gatewaymac to the encrypted query string [bluewavenet]
* Add - support for login mode in PreAuth  [bluewavenet]
* Fix - get_iface_ip in case of interface is vif or multihomed [bluewavenet]
* Fix - Add missing client identifier argument in ndsctl help text [bluewavenet]
* Fix - fix missing delimiter in fas-hid …
> opennds: Release 7.0.1

- quagga/Makefile
Commit 9a89e57d7614 ("quagga: update to 1.2.4") introduced a dependency
to libcares.
Signed-off-by: Martin Schiller <ms@dev.tdt.de>
> quagga: fix dependency to libcares

- opennds/Makefile
This version introduces major new functionality and some major changes
* Rationalisation of support for multiple Linux distributions [bluewavenet]
* Refactor login.sh script introducing base64 encoding and hashed token (hid) support [bluewavenet]
* Refactor fas-hid script introducing base64 encoding and simplifying customisation of the script [bluewavenet]
* Refactor binauth_log.sh and log BinAuth custom data as url encoded [bluewavenet]
* Refactor fas-aes, simplifying customisation of the script [bluewavenet]
* Refactor fas-aes-https, simplifying customisation of the script [bluewavenet]
* Change - Use hid instead of tok when fas_secure_enabled >= 1 [bluewavenet]
* Add - base64 encoding to fas_secure_enabled level 1 [bluewavenet]
* Add - gatewyname, clientif, session_start, session_end …
> opennds: Release 8.0.0

- babeld/Makefile
- babeld/files/babeld.config
- babeld/patches/600-add-ubus.patch
- babeld/src/ubus.c
- babeld/src/ubus.h
A better integration of babeld with OpenWrt is to connect the daemon to the ipc. So far, we can only communicate via a websocket. With ubus we can send and receive commands in json format.
> babeld: add ubus bindings

- babeld/Makefile
- babeld/patches/600-add-ubus.patch
- babeld/src/ubus.c
- babeld/src/ubus.h
Send a notification via the ubus bus if we experience any changes in neighbors, routes or xroutes.
The format looks like this:
- {route,xroute,neighbour}.add: Object was added
- {route,xroute,neighbour}.change: Object was changed
- {route,xroute,neighbour}.flush: Object was flushed
If ubus_bindings is turned off, it will minimally effect performance, since only an if-statement has to be evaluated. If no subscriber is available, it will minimally change the performance, since only an if-statmenet that checks for subscribers has to be evaluated.
> babeld: send events via ubus

- babeld/Makefile
- babeld/src/ubus.c
Fixes:
- "route_list_entry" points to "struct babel_route"
- "format_thousands" returns a string pointer
- "UBUS_METHOD_NOARG" wants a function returning an integer
> babeld: fix compiler warnings

- babeld/Makefile
- babeld/src/ubus.c
- babeld/src/ubus.h
Instead of including the headerfiles that define the structs, we add
the struct definitions to our headerfile.
Fixes warning:
```
ubus.h:67:32: warning: 'struct xroute' declared inside parameter list will not be visible outside of this definition or declaration
void ubus_notify_xroute(struct xroute *xroute, int kind);
^~~~~~
```
> babeld: adopt to upstream header-style

- alfred/Makefile
- alfred/files/alfred.init
- alfred/patches/0001-alfred-Show-error-message-for-invalid-batadv-interfa.patch
- alfred/patches/0002-alfred-Allow-exactly-one-interface-for-secondary-mod.patch
- alfred/patches/0003-alfred-Save-global-mode-flags-in-bitfield.patch
- alfred/patches/0004-alfred-Allow-start-of-server-without-valid-interface.patch
---
Alfred can be stopped during a (re)start or reload when:
* disabled = 1
* batman-adv interface is missing
* MAC based EUI64 IPv6 link-local address not set
It is assumed that procd detects that the procd instance definition disappeared and the currently running instance must be stopped. But all these checks were triggering an "exit" which then stopped the alfred init script and the wrapper from /lib/functions/procd.sh. And thus procd was never informed about the instances which should be changed.
The correct handling is to return the result of the function instead of directly killing the init scripts.
Fixes: 45db0e60d2ff ("alfred: use procd")
----
The alfred server always needs interfaces to operate on. But these interfaces might not exist at the moment when the …
> alfred: Fix state handling for startup and restart/reload of alfred

- opennds/Makefile
This release fixes an issue where some firewall rules containing
the keyword "block" would cause openNDS to fail in startup.
> opennds: Release 8.1.1

- opennds/Makefile
This release fixes an issue where some firewall rules containing
the keyword "block" would cause openNDS to fail in startup.
> opennds: Release 8.1.1 - backport from master

- opennds/Makefile
This version introduces major new functionality, some changes and fixes.
New Themed Splash pages are introduced, enabling rapid customisation. Theme placeholders can be populated from information provided in the config file. Remote files and image sources can be defined in the config file and these will be automatically downloaded as required.
Deprecated legacy code from previous versions has been removed.
Tested on OpenWrt, OpenSuse and Debian.
Signed-off-by: rob <rob@blue-wave.net>
> opennds: Release v9.0.0

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/patches/0003-batman-adv-initialize-struct-batadv_tvlv_tt_vlan_dat.patch
---
batman-adv
==========
* correctly initialize padding when sending out translation table TVLVs
* switch to AUTORELEASE to create PKG_RELEASE in OpenWrt package
batctl
====
* switch to AUTORELEASE to create PKG_RELEASE in OpenWrt package
alfred
======
* switch to AUTORELEASE to create PKG_RELEASE in OpenWrt package
> openwrt-21.02: batman-adv: Merge bugfixes from 2021.1

- .github/workflows/multi-arch-test-build.yml
The sed is adding the package name as "PKGNAME/" and does not remove the "/". That is why the buildchain currently fails.
> CI: fix building multi-arch-test-build

- babeld/Makefile
Compile tested: Trunk mips
Run-Tested: WDR4300
> babeld: add me as maintainer

- olsrd/Makefile
As a workaround for the glibc-fix the dependency on libgps was moved to olsrd. However, only pud is using this library.
> olsrd: only pud depends on libgps

- olsrd/Makefile
Use SPDX license headers to be machine readable.
> olsrd: use SPDX

- .github/issue_template
As we are the routing-feed, we don't care for packages of the base-, luci- and packages-feed.
So update the imported issue-tempalte accordingly
> issuetemplate: reference foreign repos

- opennds/Makefile
Description:
This version fixes a compiler error, some compiler warnings and mutes a debug message
* Fix - Compiler error, missing mode in call to open() [bluewave.net]
* Fix - Compiler warning, ignored return value from call to lockf() [bluewave.net]
* Fix - Compiler warning, ignored return value from call to system() [bluewave.net]
* Fix - Compiler warning, ignored return value from call to fgets() [bluewave.net]
* Fix - Remove debug message from call to get_client_interface library [bluewave.net]
> opennds: Release v9.1.1

- opennds/Makefile
Description:
This version fixes a compiler error, some compiler warnings and mutes a debug message
* Fix - Compiler error, missing mode in call to open() [bluewave.net]
* Fix - Compiler warning, ignored return value from call to lockf() [bluewave.net]
* Fix - Compiler warning, ignored return value from call to system() [bluewave.net]
* Fix - Compiler warning, ignored return value from call to fgets() [bluewave.net]
* Fix - Remove debug message from call to get_client_interface library [bluewave.net]
> [21.02] opennds: Release v9.1.1

- olsrd/files/olsrd4.init
- olsrd/files/olsrd6.init
**Urgent fix so cherry-pick also in 21.02**
Should fix #691.
Sometimes the wifi interface is not ready before olsrd tries to access
it. This leads to warnings in the form of:
daemon.info olsrd: /etc/rc.d/S65olsrd: olsrd_write_interface()
Warning: Interface 'wireless0' not found, skipped
daemon.notice procd: /etc/rc.d/S65olsrd: olsrd: /etc/rc.d/S65olsrd:
olsrd_write_interface() Warning: Interface 'wireless0' not found,			skipped
We make use of the "wait_for" procd command that allows us to wait for
the network before starting olsrd.
> [21.02] olsrd: fix olsrd starting before network

- olsrd/Makefile
- olsrd/files/olsrd-neigh.sh
This script originates from Freifunk Berlin. It prints a list of
all meshing neighbors known to olsrd on the command line.
Signed-off-by: Martin Hübner <martin.hubner@web.de>
Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Description:
> olsrd: add olsrd-neigh.sh

- olsrd/Makefile
- olsrd/files/olsrd-neigh.sh
This script originates from Freifunk Berlin. It prints a list of
all meshing neighbors known to olsrd on the command line.
Added: Error-checking for IPv4/IPv6-Hosts.
> [21.02] olsrd: add olsrd-neigh.sh

- opennds/Makefile
Description:
This version adds new functionality, improves performance, adds documentation and fixes an issue
* Add - new config options to ndsctl status [bluewave.net]
* Add - Readthedocs / man documentation for configuration options [bluewave.net]
* Add - Faster convergence of average rates to configured rate quotas [bluewave.net]
* Add - BinAuth parse authenticated client database for client data [bluewave.net]
* Add - Use heap allocation for http page buffer allowing large page sizes [bluewave.net]
* Fix - fail to serve downloaded images on custom themespec [bluewave.net] …
> opennds: Release v9.2.0

- opennds/Makefile
Description:
This version adds new functionality, improves performance, adds documentation and fixes an issue
* Add - new config options to ndsctl status [bluewave.net]
* Add - Readthedocs / man documentation for configuration options [bluewave.net]
* Add - Faster convergence of average rates to configured rate quotas [bluewave.net]
* Add - BinAuth parse authenticated client database for client data [bluewave.net]
* Add - Use heap allocation for http page buffer allowing large page sizes [bluewave.net]
* Fix - fail to serve downloaded images on custom themespec [bluewave.net] …
> opennds: [21.02] Backport of Release v9.2.0

- olsrd/files/olsrd.config
- olsrd/files/olsrd4.init
- olsrd/files/olsrd6.config
- olsrd/files/olsrd6.init
This increases the amount of seconds to wait before a service restart attempt from 5 to 15 seconds and allows unlimited retries. Olsrd sometimes crashes together with a network interface and 5 seconds can be too short to bring back up a crashed network interface, which is required for olsrd to restart.
Signed-off-by: Tobias Schwarz <info@tobias-schwarz.com>
> olsrd: improve respawn settings

- naywatch/Makefile
- naywatch/files/naywatch.config
- naywatch/files/naywatch.init
- naywatch/files/naywatch.sh
The network may crash on the SoCs, but the SoC itself does not. This leads to a node no longer being accessible in a mesh network.  If the node is placed in a location that is not easily accessible, e.g. in a high tower, it can cause a lot of problems. Therefore we check the link-local connectivity on the configured interfaces.
> naywatch: add naywatch

- opennds/Makefile
Description:
* Add - firewall passthrough mode for authenticated users [bluewave.net]
* Add - use configured debuglevel in authmon [bluewave.net]
* Add - automated log rotation and client_zone to binauth_log [bluewave.net]
* Add - increased timeout interval for file downloads [bluewave.net]
* Add - local interface to MeshZone and remove unneeded call to ip utility [bluewave.net]
* Add - log_mountpoint and max_log_entries options [bluewave.net]
* Add - config variables ext_interface and ext_gateway [bluewave.net]
* Add - …
> opennds: Release v9.3.0

- bird2/Makefile
- bird2/patches/000-ospf-bus-error.patch
Compile tested: IPQ806X, Netgear Nighthawk X4S R7800, 21.02-rc4
Run tested: IPQ806X, Netgear Nighthawk X4S R7800, 21.02-rc4. Bird2 now starts when OSPF v2 or v3 is configured.
Description:
On a Netgear R7800, if ospf v2 or v3 is configured in bird.conf, it fails to start with this error:
Fri Jun 11 14:41:11 2021 daemon.info bird: Started
Fri Jun 11 14:41:11 2021 kern.err kernel: [ 3500.853248] Alignment trap: not handling instruction f44c0a1f at [<00035848>] Fri Jun 11 14:41:11 2021 kern.alert kernel: [ 3500.853283] 8<--- cut here ---
Fri Jun 11 14:41:11 2021 kern.alert kernel: [ 3500.859363] Unhandled fault: alignment exception (0x801) at 0x007e0624
Fri Jun 11 14:41:11 2021 kern.alert kernel: [ 3500.862443] pgd = 0bbef4fd
Fri Jun 11 14:41:11 2021 kern.alert kernel: [ …
> bird2: Fix bus error on OSPF on IPQ806X

- bird2/Makefile
- bird2/patches/000-ospf-bus-error.patch
Compile tested: IPQ806X, Netgear Nighthawk X4S R7800, master
Run tested: IPQ806X, Netgear Nighthawk X4S R7800, master. Bird2 now starts when OSPF v2 or v3 is configured.
Description:
On a Netgear R7800, if ospf v2 or v3 is configured in bird.conf, it fails to start with this error:
Fri Jun 11 14:41:11 2021 daemon.info bird: Started
Fri Jun 11 14:41:11 2021 kern.err kernel: [ 3500.853248] Alignment trap: not handling instruction f44c0a1f at [<00035848>] Fri Jun 11 14:41:11 2021 kern.alert kernel: [ 3500.853283] 8<--- cut here ---
Fri Jun 11 14:41:11 2021 kern.alert kernel: [ 3500.859363] Unhandled fault: alignment exception (0x801) at 0x007e0624
Fri Jun 11 14:41:11 2021 kern.alert kernel: [ 3500.862443] pgd = 0bbef4fd
Fri Jun 11 14:41:11 2021 kern.alert kernel: [ …
> [master] bird2: Fix bus error on OSPF on IPQ806X

- cjdns/Makefile
- cjdns/files/cjdns.defaults
Maintainer: @wfleurant 
Environment: master / 21.02
Compile tested: NO
Run tested: NO
Description:
Since https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=4b9a67362d70c544b85078b8d5c661f43f7472d9,
uci network config interface sections use 'device' instead of 'ifname'
Even if 'device' seems to always be set by
package/base-files/files/bin/config_generate, we keep the fallbacks
in case someone install the package via opkg and has a non migrated
network config
> cjdns: fix uci-defaults

- batman-adv/patches/0001-Revert-batman-adv-genetlink-move-to-smaller-ops-wher.patch
- batman-adv/patches/0002-Revert-batman-adv-Add-new-include-for-min-max-helper.patch
- batman-adv/patches/0003-batman-adv-Fix-build-of-multicast-code-against-Linux.patch
- batman-adv/patches/0004-batman-adv-Always-send-iface-index-name-in-genlmsg.patch
- batman-adv/patches/0005-batman-adv-Avoid-WARN_ON-timing-related-checks.patch
Description:
* Avoid WARN_ON timing related checks
> openwrt-21.02: batman-adv: Merge bugfixes from 2021.2

- batman-adv/src/compat-hacks.h
Run tested: qemu-system-x86_64
The linux kernel 5.10 needs an explicit include of linux/if_bridge.h to  define br_multicast_list_adjacent and the struct br_ip_list. Otherwise the build fails with:
````
CC [M]  /home/sven/tmp/openwrt/build_dir/target-i386_pentium4_musl/linux-x86_generic/batman-adv-2021.2/net/batman-adv/bat_algo.o
In file included from <command-line>:
/home/sven/tmp/openwrt/build_dir/target-i386_pentium4_musl/linux-x86_generic/batman-adv-2021.2/compat-hacks.h: In function 'br_multicast_has_router_adjacent':
/home/sven/tmp/openwrt/build_dir/target-i386_pentium4_musl/linux-x86_generic/batman-adv-2021.2/compat-hacks.h:67:8: error: implicit declaration of function 'br_multicast_list_adjacent'; did you mean …
```
> batman-adv: Fix build against kernel 5.10

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/patches/0001-Revert-batman-adv-genetlink-move-to-smaller-ops-wher.patch
- batman-adv/patches/0003-batman-adv-Fix-build-of-multicast-code-against-Linux.patch
- batman-adv/patches/0004-Revert-batman-adv-Switch-to-kstrtox.h-for-kstrtou64.patch
- batman-adv/patches/0005-Revert-batman-adv-use-Linux-s-stdarg.h.patch
- batman-adv/src/compat-hacks.h
Description:
batman-adv
==========
* support latest kernels (4.4 - 5.15)
* reduced memory copy overhead when sending broadcasts
batctl
====
* (no changes)
alfred
======
* (no changes)
> batman-adv: update packages to version 2021.3

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.0, 19.07.8
Description:
* Add - Error message in fas-aes-https if shared key is mismatched [bluewave.net]
* Fix - and refactor error 511 page generation[bluewave.net]
* Fix - and refactor dnsmasq configuration [bluewave.net]
* Fix - Typographic error preventing RFC8910 disable [bluewave.net]
* Add - gateway address and gatewayfqdn to ndsctl json output [bluewave.net]
* Add - RFC8910 housekeeping on startup and shutdown [bluewave.net]
* Add - correctly apply dhcp option 114 for generic Linux [bluewave.net]
* Add - reading of configured …
> opennds: Release v9.4.0

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.0, 19.07.8
Description:
* Add - Error message in fas-aes-https if shared key is mismatched [bluewave.net]
* Fix - and refactor error 511 page generation[bluewave.net]
* Fix - and refactor dnsmasq configuration [bluewave.net]
* Fix - Typographic error preventing RFC8910 disable [bluewave.net]
* Add - gateway address and gatewayfqdn to ndsctl json output [bluewave.net]
* Add - RFC8910 housekeeping on startup and shutdown [bluewave.net]
* Add - correctly apply dhcp option 114 for generic Linux [bluewave.net]
* Add - reading of configured …
> opennds: Release v9.4.0 (for 21.02)

- naywatch/files/naywatch.init
Sometimes, naywatch can not handover the watchdog to procd again using ubus. We need to call the same ubus command multiple times until procd takes over control again.
> naywatch: fix procd handling

- naywatch/files/naywatch.init
Sometimes, naywatch can not handover the watchdog to procd again using
ubus. We need to call the same ubus command multiple times until procd
takes over control again.
(cherry picked from commit e35255710bda08f162a185be8c460b6a80e19fb1)
> [21.02] naywatch: fix procd handling

- naywatch/Makefile
- naywatch/files/naywatch.config
Naywatch in combination with the watchdog can be tricky and dangerous
when doing a sysupgrade. Add a warning to always stop naywatch first and
check if procd took control over the watchdog again.
Also change use_watchdog to '0'.
> naywatch: warn user

- naywatch/Makefile
- naywatch/files/naywatch.config
Naywatch in combination with the watchdog can be tricky and dangerous
when doing a sysupgrade. Add a warning to always stop naywatch first and
check if procd took control over the watchdog again.
Also change use_watchdog to '0'.
> [21.02] naywatch: warn user

- ohybridproxy/Makefile
Change log level from debug to info (upstream default) to avoid filling up syslog with query-level logging.
Maintainer: @fingon?
Description:
I have been using this package for over a year without any problem, yet the default debug level is quite annoying. Would you consider reverting to upstream default? Thanks!
> ohybridproxy: revert to default log level

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
Description:
batman-adv
==========
* support latest kernels (4.4 - 5.16)
- fix error handling during interface initialization
batctl
====
* (no changes)
alfred
======
* (no changes)
> batman-adv: update packages to version 2021.4

- batman-adv/Makefile
Commit 97d35a552ec5b6ddf7923dd2f9a8eb973526acea of musl introduced the
macros __LITTLE_ENDIAN and __BIG_ENDIAN in alltypes.h. These are pulled
into the compilation of batman-adv. This has the side effect that the
function is_multicast_ether_addr of etherdevice.h in Linux kernel is
compiled as the big endian version and so fails to work properly on
little endian devices.
This commit fixes that by preventing to pull in std includes and by
providing the minimal stdarg.h that Linux now provides with recent
versions. The included header file comes from Linux upstream commit
c0891ac15f0428ffa81b2e818d416bdf3cb74ab6.
Signed-off-by: Hendrik Borghorst <hendrikborghorst@gmail.com>
Maintainer: @ecsv , @simonwunderlich 
Compile tested: ramips/mt7621/wac124
Run tested: OpenWRT master @ …
> batman-adv: Prevent use from libc headers to not build with BIG_ENDIAN

- batman-adv/Makefile
Compile tested: OpenWrt 21.02, x86-64
Run tested: -
Description:
Commit 97d35a552ec5b6ddf7923dd2f9a8eb973526acea of musl introduced the macros __LITTLE_ENDIAN and __BIG_ENDIAN in alltypes.h. These are pulled into the compilation of batman-adv. This has the side effect that the
function is_multicast_ether_addr of etherdevice.h in Linux kernel is compiled as the big endian version and so fails to work properly onlittle endian devices.
This commits prevents pulling in header files of musl libc similar to OpenWRT commit 9ac47ee46918c45b91f4e4d1fa76b1e26b9d57fe
> openwrt-21.02: batman-adv: Prevent use from libc headers to not build with BIG_ENDIAN

- batman-adv/src/compat-hacks.h
Compile tested: x86-64
Run tested: -
Description:
The mac80211 package in OpenWrt master is now already providing helpers for the changed dev_{hold,put} behavior in Linux 5.15. It is no longer necessary to ship them as part of the batman-adv package.
> batman-adv: Drop duplicated dev_{hold,put} compat helpers

- mrd6/Makefile
uname variable needs to be overriden.
Maintainer: @sbyx 
Compile tested: macOS
ping @PolynomialDivision
> mrd6: fix compilation under macOS

- pimbd/Makefile
- pimbd/files/pimb.config
- pimbd/files/pimbd.init
Generate config file from uci and set as start config on start of pimbd.
Signed-off-by: Christian Strebe <uipo@freenet.de>
Maintainer: Pierre Pfister
Compile tested: x86_64, NF533, 21.02.1
Run tested: x86_64, NF533, 21.02.0-rc3
Description:
Enable the pimbd to load the configuration on start.
> pimbd: add config load on start

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.1, 19.07.8
Description:
* Fix - ThemeSpec file downloads when mwan3 is running [bluewavenet]
* Fix - Preemptive auth failure after previous deauth [minhng99] [bluewavenet]
From v9.5.0
* Add - use average packet size instead of MTU when implementing rate limiting [bluewavenet]
* Fix - typo in iptables command and remove a redundant command [bluewavenet]
* Add - startdaemon() and stopdaemon() utility functions [bluewavenet]
* Add - combined interface/ipaddress external gateway status monitoring [bluewavenet]
* Fix - potential online/offline …
> opennds: Release v9.5.1 (for 21.02)

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.1, 19.07.8
Description:
* Fix - ThemeSpec file downloads when mwan3 is running [bluewavenet]
* Fix - Preemptive auth failure after previous deauth [minhng99] [bluewavenet]
From v9.5.0
* Add - use average packet size instead of MTU when implementing rate limiting [bluewavenet]
* Fix - typo in iptables command and remove a redundant command [bluewavenet]
* Add - startdaemon() and stopdaemon() utility functions [bluewavenet]
* Add - combined interface/ipaddress external gateway status monitoring [bluewavenet]
* Fix - potential online/offline …
> opennds: Release v9.5.1

- olsrd/files/olsrd.sh
The procd script was not adding the wireguard interfaces. Add corner case in the init script to allow meshing via wireguard.
> olsrd: fix meshing via wireguard tunnels

- olsrd/files/olsrd.sh
The procd script was not adding the wireguard interfaces. Add corner case
in the init script to allow meshing via wireguard.
(cherry picked from commit 576967a2a3eaa468bcba2f24708ea4674b7e3586)
> [21.02] olsrd: fix meshing via wireguard tunnels

- naywatch/files/naywatch.sh
The if-condition was always evaluated to be true.
> naywatch: fix mode without watchdog

- naywatch/files/naywatch.sh
Check multiple rounds if neighbors are available before kicking. This should reduce unneeded reboots.
(cherry picked from commit 24285ce4fcd56aa806bdbe9ac16cbfed0a81d2f8)
> [21.02] naywatch: introduce kick-count

- .github/workflows/multi-arch-test-build.yml
The runtime testing always ran on master branch aka snapshots since the
branch wasn't passed over to the container execution!
> CI: fix runtime testing for non master branch

- .github/workflows/multi-arch-test-build.yml
The runtime testing always ran on master branch aka snapshots since the
branch wasn't passed over to the container execution!
Signed-off-by: Paul Spooren <mail@aparcar.org>
(cherry picked from commit 817240b07c7158c72de427051eb9bae1c39b3abe)
> [21.02] CI: fix runtime testing for non master branch

- olsrd/Makefile
- olsrd/patches/100-rename-avl-to-olsrd_avl.patch
- olsrd/patches/101-unix-fix-meshing-with-wireguard-point-to-point-interfaces.patch
- olsrd/patches/600-add-ubus-support.patch
- olsrd/src/src/ubus.c
- olsrd/src/src/ubus.h
IPC integration of olsrd with OpenWrt. Allow dynamic adding and removing
of interfaces at run-time. We need to rename the avl-tree files, since
libubox also defines avl tree. Also add patch to allow meshing via
wireguard point-to-point links.
The ubus interface offers following functions:
- add_inteface '{"ifname":"wg_51820"}'
- del_inteface '{"ifname":"wg_51820"}'
> olsrd: add ubus ipc integration to olsrd

- olsrd/Makefile
- olsrd/patches/100-rename-avl-to-olsrd_avl.patch
- olsrd/patches/101-unix-fix-meshing-with-wireguard-point-to-point-interfaces.patch
- olsrd/patches/600-add-ubus-support.patch
- olsrd/src/src/ubus.c
- olsrd/src/src/ubus.h
IPC integration of olsrd with OpenWrt. Allow dynamic adding and removing
of interfaces at run-time. We need to rename the avl-tree files, since
libubox also defines avl tree. Also add patch to allow meshing via
wireguard point-to-point links.
The ubus interface offers following functions:
- add_inteface '{"ifname":"wg_51820"}'
- del_inteface '{"ifname":"wg_51820"}'
(cherry picked from commit 0bffe620b441c039780d4336a15c8ed4f2ebbbf4)
> [21.02] olsrd: add ubus ipc integration to olsrd

- babeld/src/ubus.c
- babeld/src/ubus.h
An interface can be added dynmiacally to babeld by starting babeld with
the local management interface (-G) and saying:
interface eth0
Add the ubus equivalent of this function:
ubus call babeld add_interface '{"ifname":"eth0"}'
> babeld: add add_interface function

- babeld/src/ubus.c
There is an unused variable in the function. Remove it.
Fixes: 385200443554 ("babeld: add add_interface function").
> babeld: remove unused return variable

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
batman-adv
==========
* support latest kernels (4.9 - 5.17)
* dropped support for kernels < 4.9
* allow netlink usage in unprivileged containers
- don't send link-local multicast to mcast routers
batctl
====
* (no changes)
alfred
======
* allow changing of batman-adv interface at runtime
* allow to start alfred without interfaces specified
> batman-adv: update packages to version 2022.0

- batman-adv/patches/0007-batman-adv-allow-netlink-usage-in-unprivileged-conta.patch
- batman-adv/patches/0008-batman-adv-mcast-don-t-send-link-local-multicast-to-.patch
Description:
* allow netlink usage in unprivileged containers
* mcast: don't send link-local multicast to mcast routers
> openwrt-21.02: batman-adv: Merge bugfixes from 2022.0

- olsrd/src/src/ubus.c
The IPC should apply the "InterfaceDefaults".
> olsrd: fix setting default interface config

- olsrd/src/src/ubus.c
The IPC should apply the "InterfaceDefaults".
(cherry picked from commit 4afbe1748020e1677ec5529198d92e1870d3c012)
> [21.02] olsrd: fix setting default interface config

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.1, 19.07.8
Description:
* Fix - correctly display return buffer in syslog [bluewavenet]
* Add - use heap allocation for library call return buffer [bluewavenet]
* Fix - OpenWrt, fhook request for fw3 [bluewavenet]
* Add - spider remote urls before downloading [bluewavenet]
* Add - OpenWrt, revert uncommitted uci updates at startup and shutdown [bluewavenet]
* Fix - remove unneccesary flash writes and fix hosts updates [doctor-ox] [bluewavenet]
* Add - Updated splash images [bluewavenet]
* Add - OpenWrt makefile for nft or ipt dependencies …
> opennds: Release v9.6.0

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, gl-inet b1300, gl-inet mt300n-v2, Snapshot, 21.02.1, 19.07.8
Description:
It requires iptables(legacy)
* Fix - correctly display return buffer in syslog [bluewavenet]
* Add - use heap allocation for library call return buffer [bluewavenet]
* Fix - OpenWrt, fhook request for fw3 [bluewavenet]
* Add - spider remote urls before downloading [bluewavenet]
* Add - OpenWrt, revert uncommitted uci updates at startup and shutdown [bluewavenet]
* Fix - remove unneccesary flash writes and fix hosts updates [doctor-ox] [bluewavenet]
* Add - Updated splash images [bluewavenet]
* Add - OpenWrt makefile …
> opennds: Release v9.6.0 (for 21.02)

- bmx6/Makefile
Maintainer: N/A
Compile tested: Turris Omnia, mvebu/cortex-a9, OpenWrt master
**Description:**
Makefile polishing:
- Fixed SPDX License Identifier
- Use AUTORELEASE in PKG_RELEASE
This helps in cases when the PKG_RELEASE is forgotten
- Remove no longer used things like PKG_REV, etc.
Downloaded tarball is now ~80 kB smaller as we use .tar.xz
instead of .tar.gz
> bmx6: update to 65cb0d542f16a4b4689f5ad2542c9f24215a6616

- pimbd/Makefile
Maintainer: N/A
Compile tested: Turris Omnia, mvebu/cortex-a9, OpenWrt master
Description:
- Switch to AUTORELEASE
- There was no need to overwrite defaults, downloaded tarball is ~4 kB
smaller
Also change the package versioning
Before: pimbd_2018-06-19-dbf4e5913b06e3160f506df15e6a047a403a5f21-2_arm_cortex-a9_vfpv3-d16.ipk
After: pimbd_2018-06-19-dbf4e591-1_arm_cortex-a9_vfpv3-d16.ipk
- Add PKG_LICENSE_FILES
> pimbd: Makefile refactor

- mcproxy/Makefile
Maintainer: is not active
Compile tested: Turris Omnia, OpenWrt master, mvebu_cortex-a9
Description:
- Switched to AUTORELEASE
- Fixed SPDX License Identifier and added PKG_LICENSE_FILES
- Use HTTPS for project website
- Changed versioning
Before: mcproxy_2017-08-24-93b5ace42268160ebbfff4c61818fb15fa2d9b99-3_arm_cortex-a9_vfpv3-d16.ipk
After: mcproxy_2017-08-24-93b5ace4-1_arm_cortex-a9_vfpv3-d16.ipk
Downloaded tarball is smaller by 0,2 MB
> mcproxy: Makefile cleanup

- ahcpd/Makefile
- The old page redirects to a new one and it uses HTTPS.
Let's skip that redirect in PKG_SOURCE_URL and URL.
- Reorder some things to be sync with Makefiles in packages feed
- Add PKG_LICENSE_FILES
Fixes: 47edf2d27594083f91777913bbe57c43a2927f09 (ahcpd: Replace
PKG_MD5SUM with PKG_HASH)
(cherry picked from commit 6debd2f564ce1ffed6b397c79bd4d6fa60ad30e2)
> [19.07] ahcpd: use SHA256 hash and use HTTPS everywhere

- prince/Makefile
Maintainer: @gabri94
Compile tested: Turris Omnia, OpenWrt master, mvebu/cortex-a9
Description:
- Use AUTORELEASE in PKG_RELEASE
- Use tarball instead of checkouting git
- Use two spaces instead of indentation
- In install section reorder it (first folder, then files and so on)
- Added LICENSE file
- Reorder things to be more consistent with others
> prince: Makefile refactoring

- nodogsplash/Makefile
Maintainer: @mwarning 
Compile and run tested: N/A, just reordering
Description:
- Add PKG_LICENSE_FILES
- Use two spaces instead of tabs
> nodogsplash: fix SPDX License Identifier and reordering

- minimalist-pcproxy/Makefile
Maintainer: @fingon 
Compile tested: Turris Omnia, mvebu-cortexa9/OpenWrt master
Description:
- Fixed LICENSE
Software is licensed under MIT
- Added PKG_LICENSE_FILES
- The was wrong date in PKG_VERSION
The latest commit is 2014-12-12.
- Changed package versioning
Before: minimalist-pcproxy_2015-01-12-2d6d1b0b0a3b79a9b4a9b0a7606a84600a967bcb-2_arm_cortex-a9_vfpv3-d16.ipk
After: minimalist-pcproxy_2014-12-12-2d6d1b0b-1_arm_cortex-a9_vfpv3-d16.ipk
Also the downloaded tarball is smaller by 0,4 kB
> minimalist-pcproxy: Makefile cleanup

- minimalist-pcproxy/files/minimalist-pcproxy.defaults
Maintainer: @sbyx 
Compile tested: Turris 1.1, powerpc8540, OpenWrt 21.02.2
Run tested: Turris 1.1, powerpc8540, OpenWrt master
Fixes: https://github.com/openwrt/routing/issues/149
Would be nice to remove backtics, but this is fine as it is.
This should be cherry-picked to OpenWrt 21.02 and OpenWrt 19.07 branches.
> minimalist-pcproxy: fix post install script

- olsrd/Makefile
Firewall4 uses nftables instead of iptables. Use iptables-nft for installing smart-gw-rules.
Fixes: #731 ("Certain upstream switch to firewall4 aka nftables instead of iptables")
> olsrd: switch to firewall4

- cjdns/Makefile
- cjdns/files/cjdns.defaults
Since https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=4b9a67362d70c544b85078b8d5c661f43f7472d9,
uci network config interface sections use 'device' instead of 'ifname'
Even if 'device' seems to always be set by
package/base-files/files/bin/config_generate, we keep the fallbacks
in case someone install the package via opkg and has a non migrated
network config
Signed-off-by: Etienne Champetier <champetier.etienne@gmail.com>
(cherry picked from commit 383c52ff8d9c0577a262d014aca66bd4095f4e38)
> [21.02] cjdns: fix uci-defaults (#714)

- vis/Makefile
- vis/patches/0001-Allow-one-to-disable-forking-to-background-in-debug_.patch
Maintainer: @elektra42
Compile tested: Turris Omnia, OpenWrt master, mvebu/cortex-a9
Description:
- Update it from https://git.open-mesh.org/vis.git/commit/e141311c6a4fc824efbad536c137ed279905d825 to https://git.open-mesh.org/vis.git/commit/7710cce42e8d63ea114056a4a140835d4a452933
- Switch to AUTORELEASE in PKG_RELEASE
This avoids cases when someone forgets to bump PKG_RELEASE
- Fixed SPDX License Identifier
- Changed package versioning
Before: vis_1440-2_arm_cortex-a9_vfpv3-d16.ipk
After: vis_2013-04-07-7710cce4-1_arm_cortex-a9_vfpv3-d16.ipk
- Drop not necessary rows
(Some of them were overwritting defaults and it is not necessary)
Downloaded tarball is ~2kB smaller
> vis: update, refactor Makefile and refresh patch due to fuzz

- cjdns/Makefile
Compile time changes reviewed by cjd.
Due to stricter compiler(s) we do not
want to error for these warnings.
Caused by: ...reading "past the end"
of a struct, because the struct is
actually a header and the body is of
unknown size. Compilers got stricter
and this became a warning.
(cherry picked from commit 71c11ab1b7d7f6ca3219c1359e20b168ec1979c5)
> [21.02] cjdns: pass for some build warnings (#738)

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on snapshot
* Fix - syntax error (missing comma) in awk command in bash on generic Linux [bluewavenet]
* Add - option to append serial number suffix to gatewayname [bluewavenet]
* Add - block use of ip aliases on gateway interface [doctor-ox] [bluewavenet]
* Fix - ndsctl json syntax error [bluewavenet]
* Add - check for null variables in key value pairs in MHD callbacks [bluewavenet]
* Fix - changed some notice messages into debug messages [bluewavenet]
* Fix - possible return of incorrect pid [doctor-ox] [bluewavenet]
* Fix - possible abiguities resulting in failure to parse …
> opennds: Release v9.7.0

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02.2
Description:
It requires iptables(legacy)
* Fix - syntax error (missing comma) in awk command in bash on generic Linux [bluewavenet]
* Add - option to append serial number suffix to gatewayname [bluewavenet]
* Add - block use of ip aliases on gateway interface [doctor-ox] [bluewavenet]
* Fix - ndsctl json syntax error [bluewavenet]
* Add - check for null variables in key value pairs in MHD callbacks [bluewavenet]
* Fix - changed some notice messages into debug messages [bluewavenet]
* Fix - possible return of incorrect pid [doctor-ox] [bluewavenet]
* Fix - possible …
> opennds: Release v9.7.0 (for 21.02)

- olsrd/src/src/ubus.c
- olsrd/src/src/ubus.h
You can now give a lqm when adding an interface:
ubus call olsrd add_interface '{"ifname":"wg_51821", "lqm":"0.5"}'
> olsrd: set lqm via ipc

- olsrd/src/src/ubus.c
- olsrd/src/src/ubus.h
You can now give a lqm when adding an interface:
ubus call olsrd add_interface '{"ifname":"wg_51821", "lqm":"0.5"}'
(cherry picked from commit e3c68429239f77c895b32502e2609df8b72c6caa)
> [21.02] olsrd: set lqm via ipc

- olsrd/src/src/ubus.c
- olsrd/src/src/ubus.h
You can now give a lqm when adding an interface:
ubus call olsrd add_interface '{"ifname":"wg_51821", "lqm":"0.5"}'
(cherry picked from commit e3c68429239f77c895b32502e2609df8b72c6caa)
> [22.03] olsrd: set lqm via ipc

- babeld/patches/000-export-add-filters-and-simplify-interface.patch
- babeld/patches/600-add-ubus.patch
- babeld/src/ubus.c
- babeld/src/ubus.h
I just tried to add simple filter. However, this does not work. Any idea what is missing to add a filter @jech?
E.g.
in if eth0 metric 128
should be
ubus call babeld add_filter '{"ifname":"eth0", "type":"input", "metric":128}'
> babeld: add add_filter function

- babeld/patches/000-export-add-filters-and-simplify-interface.patch
- babeld/patches/600-add-ubus.patch
- babeld/src/ubus.c
- babeld/src/ubus.h
You can define filter functions in babeld by:
in if eth0 metric 128
This commit adds the ubus equivalent to dynamically add filter on
runtime:
ubus call babeld add_filter '{"ifname":"eth0", "type":"input",
"metric":128}'
(cherry picked from commit a618159d33e02e9a295388e605447993eca11e52)
Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Description:
> [21.02] babeld: add add_filter function

- babeld/patches/000-export-add-filters-and-simplify-interface.patch
- babeld/patches/600-add-ubus.patch
- babeld/src/ubus.c
- babeld/src/ubus.h
You can define filter functions in babeld by:
in if eth0 metric 128
This commit adds the ubus equivalent to dynamically add filter on
runtime:
ubus call babeld add_filter '{"ifname":"eth0", "type":"input",
"metric":128}'
(cherry picked from commit a618159d33e02e9a295388e605447993eca11e52)
> [22-03] babeld: add add_filter function

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02.2 and snapshot.
Description:
Mesh11sd is a dynamic parameter configuration daemon for 802.11s mesh networks.
It was originally designed to leverage 802.11s mesh networking at Captive Portal venues.
This is the open source version and it enables easy and automated mesh network operation with multiple mesh nodes.
It allows all mesh parameters supported by the wireless driver to be set in the uci config file.
Settings take effect immediately without having to restart the wireless network.
Default settings give rapid and reliable layer 2 mesh convergence.
Without mesh11sd, many mesh parameters cannot be set in the uci wireless config file as the mesh interface must …
> mesh11sd: [New Package] Release v1.0.0

- naywatch/files/naywatch.sh
Naywatch should first try to reboot normally, and if that does not work do a hard reboot. However, the hard reboot was never called.
> naywatch: fix reboot_now

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on snapshot
* Fix - syntax error (missing comma) in awk command in bash on generic Linux [bluewavenet]
* Add - option to append serial number suffix to gatewayname [bluewavenet]
* Add - block use of ip aliases on gateway interface [doctor-ox] [bluewavenet]
* Fix - ndsctl json syntax error [bluewavenet]
* Add - check for null variables in key value pairs in MHD callbacks [bluewavenet]
* Fix - changed some notice messages into debug messages [bluewavenet]
* Fix - possible return of incorrect pid [doctor-ox] [bluewavenet]
* Fix - possible abiguities resulting in failure to parse …
> [22.03] opennds: Release v9.7.0 Backport

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02.2
Description:
Mesh11sd is a dynamic parameter configuration daemon for 802.11s mesh networks.
It was originally designed to leverage 802.11s mesh networking at Captive Portal venues.
This is the open source version and it enables easy and automated mesh network operation with multiple mesh nodes.
It allows all mesh parameters supported by the wireless driver to be set in the uci config file.
Settings take effect immediately without having to restart the wireless network.
Default settings give rapid and reliable layer 2 mesh convergence.
Without mesh11sd, many mesh parameters cannot be set in the uci wireless config file as the mesh interface must be up before …
> [21.02] mesh11sd: [New Package] Release v1.0.0

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02.2
Description:
Mesh11sd is a dynamic parameter configuration daemon for 802.11s mesh networks.
It was originally designed to leverage 802.11s mesh networking at Captive Portal venues.
This is the open source version and it enables easy and automated mesh network operation with multiple mesh nodes.
It allows all mesh parameters supported by the wireless driver to be set in the uci config file.
Settings take effect immediately without having to restart the wireless network.
Default settings give rapid and reliable layer 2 mesh convergence.
Without mesh11sd, many mesh parameters cannot be set in the uci wireless config file as the mesh interface must be up before …
> [22.03] mesh11sd: [New Package] Release v1.0.0

- batman-adv/patches/0009-batman-adv-make-mc_forwarding-atomic.patch
- batman-adv/patches/0010-batman-adv-compat-Add-atomic-mc_fowarding-support-fo.patch
Run tested: -
Description:
Eric Dumazet changed the mc_forwarding in commit 145c7a793838 ("ipv6: make mc_forwarding atomic") the type of mc_forwarding from __s32 to an atomic_t. This patch was then ported to various stable kernels.
This code change caused a FTBFS when in batman-adv when `CONFIG_BATMAN_ADV_MCAST` was activated. To work around this problem, provide a version for kernels with __s32 mc_forwarding and a version for kernel with atomic_t mc_forwarding.
Fixes: #850
> openwrt-21.02: batman-adv: compat: Add atomic mc_forwarding support for stable kernels

- batman-adv/patches/0006-batman-adv-make-mc_forwarding-atomic.patch
- batman-adv/patches/0007-batman-adv-compat-Add-atomic-mc_fowarding-support-fo.patch
Run tested: -
Description:
Eric Dumazet changed the mc_forwarding in commit 145c7a793838 ("ipv6: make mc_forwarding atomic") the type of mc_forwarding from __s32 to an atomic_t. This patch was then ported to various stable kernels.
This code change caused a FTBFS when in batman-adv when `CONFIG_BATMAN_ADV_MCAST` was activated. To work around this problem, provide a version for kernels with __s32 mc_forwarding and a version for kernel with atomic_t mc_forwarding.
Fixes: #850
> openwrt-22.03: batman-adv: compat: Add atomic mc_forwarding support for stable kernels

- babeld/Makefile
- babeld/patches/600-add-ubus.patch
Changelog:
5 May 2022: babeld-1.12
* Implement v4-via-v6 routing (RFC 9229), which allows a router with
IPv4 addresses only to route IPv4.  Thanks to Théophile Bastian.
* Enable extended Netlink acks when available.
Thanks to Toke Høyland-Jørgensen.
* Fix restoring of interface configuration to avoid unbounded memory
consumption.  Thanks to andrew-hoff.
* Fix handling of deny filters in the install chain.
Refreshed patches:
- 600-add-ubus.patch
> babeld: update to 1.12

- babeld/Makefile
- babeld/patches/600-add-ubus.patch
Changelog:
5 May 2022: babeld-1.12
* Implement v4-via-v6 routing (RFC 9229), which allows a router with
IPv4 addresses only to route IPv4.  Thanks to Théophile Bastian.
* Enable extended Netlink acks when available.
Thanks to Toke Høyland-Jørgensen.
* Fix restoring of interface configuration to avoid unbounded memory
consumption.  Thanks to andrew-hoff.
* Fix handling of deny filters in the install chain.
Refreshed patches:
- 600-add-ubus.patch
> [22.03] babeld: update to 1.12

- babeld/Makefile
- babeld/patches/600-add-ubus.patch
Changelog:
5 May 2022: babeld-1.12
* Implement v4-via-v6 routing (RFC 9229), which allows a router with
IPv4 addresses only to route IPv4.  Thanks to Théophile Bastian.
* Enable extended Netlink acks when available.
Thanks to Toke Høyland-Jørgensen.
* Fix restoring of interface configuration to avoid unbounded memory
consumption.  Thanks to andrew-hoff.
* Fix handling of deny filters in the install chain.
Refreshed patches:
- 600-add-ubus.patch
> [21.02] babeld: update to 1.12

- alfred/patches/0001-alfred-Ensure-processed-change_iface-packet-is-0-ter.patch
- alfred/patches/0002-alfred-Ensure-processed-change_bat_iface-packet-is-0.patch
- batctl/patches/0001-batctl-ping-Skip-sleep-after-last-packet.patch
- batman-adv/patches/0008-batman-adv-Request-iflink-once-in-batadv-on-batadv-c.patch
- batman-adv/patches/0009-batman-adv-Request-iflink-once-in-batadv_get_real_ne.patch
- batman-adv/patches/0010-batman-adv-Don-t-expect-inter-netns-unique-iflink-in.patch
- batman-adv/patches/0011-batman-adv-Don-t-skb_split-skbuffs-with-frag_list.patch
batman-adv
==========
* Request iflink once in batadv-on-batadv check
* Request iflink once in batadv_get_real_netdevice
* Don't expect inter-netns unique iflink indices
* Don't skb_split skbuffs with frag_list
batctl
====
*  ping: Skip sleep after last packet
alfred
======
* Ensure processed change_iface packet is 0-terminated
* Ensure processed change_bat_iface packet is 0-terminated
> openwrt-22.03: batman-adv: Merge bugfixes from 2022.0

- batman-adv/src/compat-hacks.h
Compile tested: mt7622
@ptpt52
The build failed in this kernel due to some missing implicit includes:
build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/batman-adv-2022.1/compat-hacks.h:64:42: warning: 'struct sk_buff' declared inside parameter list will not be visible outside of this definition or declaration
64 | static inline int batadv_netif_rx(struct sk_buff *skb)
|                                          ^~~~~~~
build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/batman-adv-2022.1/compat-hacks.h: In function 'batadv_netif_rx':
build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_mt7622/batman-adv-2022.1/compat-hacks.h:66:13: error: implicit declaration of function 'in_interrupt' [-Werror=implicit-function-declaration]
66 | …
> batman-adv: Fix build with kernel 5.15.38

- babeld/Makefile
Changelog:
916d3d9 Update CHANGES for babeld-1.12.1
3d8aec4 Schedule an interface check after adding an interface.
f13602b Split last PC into unicast and multicast values
(cherry picked from commit 9028f67afd88bbd46edde265bfc77e705406cbc4)
> [21.02] babled: update to 1.12.1

- babeld/Makefile
Changelog:
916d3d9 Update CHANGES for babeld-1.12.1
3d8aec4 Schedule an interface check after adding an interface.
f13602b Split last PC into unicast and multicast values
> [22.03] babled: update to 1.12.1

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02.2 and snapshot.
Description:
* This version adds new functionality, and fixed some issues
* Fix - repeated syslog messages - output only on mode change [bluewavenet]
* Add - service status to json output [bluewavenet]
* Add - support for multiple mesh interfaces [bluewavenet]
* Fix - duplicate ifname if more than one mesh interface [bluewavenet]
* Add - compatibility with iw < v5.16-1 [bluewavenet]
* Add - search and delete phantom meshnodes [bluewavenet]
> mesh11sd: Release v1.1.1

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02.2 and snapshot.
Description:
* This version adds new functionality, and fixed some issues
* Fix - repeated syslog messages - output only on mode change [bluewavenet]
* Add - service status to json output [bluewavenet]
* Add - support for multiple mesh interfaces [bluewavenet]
* Fix - duplicate ifname if more than one mesh interface [bluewavenet]
* Add - compatibility with iw < v5.16-1 [bluewavenet]
* Add - search and delete phantom meshnodes [bluewavenet]
(cherry picked from commit 1cd90655dabb22d74d010b589d884a9c0c3d7c8b)
> mesh11sd: [22.03] Release v1.1.1

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64, on 21.02.2 and snapshot.
Description:
* This version adds new functionality, and fixed some issues
* Fix - repeated syslog messages - output only on mode change [bluewavenet]
* Add - service status to json output [bluewavenet]
* Add - support for multiple mesh interfaces [bluewavenet]
* Fix - duplicate ifname if more than one mesh interface [bluewavenet]
* Add - compatibility with iw < v5.16-1 [bluewavenet]
* Add - search and delete phantom meshnodes [bluewavenet]
(cherry picked from commit 1cd90655dabb22d74d010b589d884a9c0c3d7c8b)
> mesh11sd: [21.02] Release v1.1.1

- .github/workflows/multi-arch-test-build.yml
The previous build errors with v5 have been fixed. This version builds
packages as a normal user instead of as root.
> ci: Use openwrt/gh-action-sdk@v5

- naywatch/files/naywatch.sh
Naywatch now prints
naywatch: Naywatch Activated!
when becoming active.
(cherry picked from commit 09d5ceb9230b907029a3e09858ef181ff85e3913)
> [21.02] naywatch: add log when naywatch activates

- naywatch/files/naywatch.sh
Naywatch now prints
naywatch: Naywatch Activated!
when becoming active.
(cherry picked from commit 09d5ceb9230b907029a3e09858ef181ff85e3913)
> [22.03] naywatch: add log when naywatch activates

- cjdns/Makefile
- cjdns/lua/cjdns/uci.lua
- luci-app-cjdns/Makefile
- luci-app-cjdns/luasrc/model/cbi/cjdns/peering.lua
Maintainer: me
Compile tested: OpenWrt Trunk
Run tested: Tested on Raspi4 device with v21.1
Description: configure cjdns with a given list of supernodes peers
> cjdns: support the supernodes feature

- bird2/Makefile
Signed-off-by: Jan Betik <jan.betik@nic.cz>
Description: bump to 2.0.10
> bird2: bump to version 2.0.10

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
batman-adv
==========
* support latest kernels (4.9 - 5.19)
alfred
======
* support event notification via unix socket
* improve timing stability of transmitted announcement packets
* reduce socket handling overhead when many clients and interfaces
> batman-adv: update packages to version 2022.2

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on snapshot, 22.03
* Fix - suppress stderr in client_params in generic linux [bluewavenet]
* Fix - client_params on generic linux, remote logo not supported yet [bluewavenet]
* Fix - compiler warning [bluewavenet]
* Fix - set voucher script as executable [bluewavenet]
* Update OpenWrt Makefile [bluewavenet]
* Add - format footer in Themespec scripts [bluewavenet]
* Update footer on all scripts [bluewavenet]
* Update - Community Voucher Themespec [bluewavenet]
* Add - Check on startup for Y2.038K bug (32 bit time) [bluewavenet]
* Fix - Remove deprecated Debian specific …
> opennds: Release v9.8.0

- mesh11sd/Makefile
Description:
* This version adds new functionality.
* Update README.md
* Add - Traffic volume, Peers and stations to status output [bluewavenet]
* Add - limit up-checks to mesh interfaces only [bluewavenet]
-- Rob White <dot@blue-wave.net>  Mon, 08 Aug 2022 13:40:31 +0000
> mesh11sd: Release v1.2.0

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on 21.02
* Fix - suppress stderr in client_params in generic linux [bluewavenet]
* Fix - client_params on generic linux, remote logo not supported yet [bluewavenet]
* Fix - compiler warning [bluewavenet]
* Fix - set voucher script as executable [bluewavenet]
* Update OpenWrt Makefile [bluewavenet]
* Add - format footer in Themespec scripts [bluewavenet]
* Update footer on all scripts [bluewavenet]
* Update - Community Voucher Themespec [bluewavenet]
* Add - Check on startup for Y2.038K bug (32 bit time) [bluewavenet]
* Fix - Remove deprecated Debian specific files …
> opennds: Release v9.8.0 [21.02]

- opennds/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on snapshot, 22.03
* Fix - suppress stderr in client_params in generic linux [bluewavenet]
* Fix - client_params on generic linux, remote logo not supported yet [bluewavenet]
* Fix - compiler warning [bluewavenet]
* Fix - set voucher script as executable [bluewavenet]
* Update OpenWrt Makefile [bluewavenet]
* Add - format footer in Themespec scripts [bluewavenet]
* Update footer on all scripts [bluewavenet]
* Update - Community Voucher Themespec [bluewavenet]
* Add - Check on startup for Y2.038K bug (32 bit time) [bluewavenet]
* Fix - Remove deprecated Debian specific …
> [22.03] opennds: Release v9.8.0

- mesh11sd/Makefile
Description:
* This version adds new functionality.
* Update README.md
* Add - Traffic volume, Peers and stations to status output [bluewavenet]
* Add - limit up-checks to mesh interfaces only [bluewavenet]
-- Rob White <dot@blue-wave.net>  Mon, 08 Aug 2022 13:40:31 +0000
(cherry picked from commit 290ed82bd8b8b2d4153721aa073456d5089da73b)
> [22.03] mesh11sd: Release v1.2.0

- mesh11sd/Makefile
Description:
* This version adds new functionality.
* Update README.md
* Add - Traffic volume, Peers and stations to status output [bluewavenet]
* Add - limit up-checks to mesh interfaces only [bluewavenet]
-- Rob White <dot@blue-wave.net>  Mon, 08 Aug 2022 13:40:31 +0000
(cherry picked from commit 290ed82bd8b8b2d4153721aa073456d5089da73b)
> [21.02] mesh11sd: Release v1.2.0

- opennds/Makefile
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64 Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on snapshot, 22.03
opennds (9.9.0)
* Add - Community ThemeSpec to support legacy splash.html [bluewavenet]
* Fix - ensure nat_traversal_poll_interval defaults to 10 seconds [bluewavenet]
* Add - process send_to_fas_deauthed and send_to_fas_custom in fas-aes-https [bluewavenet]
* Add - support for send_to_fas_deauthed library call in binauth_log.sh [bluewavenet]
* Add - heartbeat file containing timestamp [bluewavenet]
* Add - send_to_fas_deauthed and send_to_fas_custom library calls [bluewavenet]
* Add - Save authmon daemon startup arguments for libopennds [bluewavenet] …
> opennds: Release v9.9.0

- opennds/Makefile
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64 Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on snapshot, 22.03
opennds (9.9.0)
* Add - Community ThemeSpec to support legacy splash.html [bluewavenet]
* Fix - ensure nat_traversal_poll_interval defaults to 10 seconds [bluewavenet]
* Add - process send_to_fas_deauthed and send_to_fas_custom in fas-aes-https [bluewavenet]
* Add - support for send_to_fas_deauthed library call in binauth_log.sh [bluewavenet]
* Add - heartbeat file containing timestamp [bluewavenet]
* Add - send_to_fas_deauthed and send_to_fas_custom library calls [bluewavenet]
* Add - Save authmon daemon startup arguments for libopennds [bluewavenet] …
> [22.03] opennds: Release v9.9.0

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/patches/0004-Revert-batman-adv-Migrate-to-linux-container_of.h.patch
- batman-adv/src/compat-hacks.h
batman-adv
==========
* support latest kernels (4.9 - 6.1)
- limit the minimum MTU of hard-interface to avoid "Forced to purge local tt entries" errors
alfred
======
> batman-adv: update packages to version 2022.3

- opennds/Makefile
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64 Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on snapshot, 22.03
opennds (9.9.1)
* This version fixes some issues
* Fix - minimalise deprecated legacy .conf file
* Fix - Prevent rate limit refresh if rate limit is set to 0 [bluewavenet]
* Fix - Mute some unneccessary debug messages [bluewavenet]
* Fix - do not write unconfigured (null) parameters to client id file (cidfile) [bluewavenet]
* Fix - Prevent error "Command process exited due to signal 13" when executing an external script [bluewavenet]
* Fix - use WTERMSIG() return code for _execute_ret when execute fails [bluewavenet]
* Fix - use correct response type for error 503 [bluewavenet]
* Update Makefile description …
> opennds: Release v9.9.1

- bird1-openwrt/bird1-ipv4-openwrt/Makefile
- bird1-openwrt/bird1-ipv6-openwrt/Makefile
Maintainer: @eloicaso
See https://forum.openwrt.org/t/luci-app-bird1-ipv4-errors/70288
> bird1: Add missing dependency on luci-compat

- bmx7/Makefile
Bump PKG_RELEASE for libiwinfo ABI change for bmx7 package.
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>
> bmx7: bump PKG_RELEASE for libiwinfo ABI change

- opennds/Makefile
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64 Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, x86-64; on snapshot, 22.03
opennds (9.10.0)
* Fix - unable to read client upload traffic volume on some versions of iptables-nft (generic Linux) [bluewavenet]
* Fix - compatibility with bash shell on generic Linux [bluewavenet]
* Fix - compiler warning, unused variable [bluewavenet]
* Fix - silently continue if fw4 table is not found [bluewavenet]
* Add - Start daemon earlier on boot [bluewavenet]
* Fix - compatibility with legacy iptables packages [bluewavenet]
* Add - call to delete nft chains [bluewavenet]
* Fix - stop using legacy INPUT and FORWARD chains [bluewavenet]
* Add …
> opennds: Release v9.10.0

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/src/compat-hacks.h
batman-adv
==========
* support latest kernels (4.14 - 6.2)
alfred
======
* add support for gpsd 3.25
> batman-adv: update packages to version 2023.0

- babeld/Makefile
Release announcement:
https://alioth-lists.debian.net/pipermail/babel-users/2023-February/004038.html
> babeld: update to 1.12.2

- babeld/Makefile
Release announcement:
https://alioth-lists.debian.net/pipermail/babel-users/2023-February/004038.html
(cherry picked from commit bb65c3a18d509874b6b4c6bbb1ad779ae667c0ed)
> [21.02] babeld: update to 1.12.2

- babeld/Makefile
> [21.02] babeld: remove AUTORELEASE

- babeld/Makefile
Release announcement:
https://alioth-lists.debian.net/pipermail/babel-users/2023-February/004038.html
(cherry picked from commit bb65c3a18d509874b6b4c6bbb1ad779ae667c0ed)
> [22.03] babeld: update to 1.12.2

- oonf-olsrd2/Config.in
- oonf-olsrd2/Makefile
Signed-off-by: Patrick Grimm <patrick@lunatiki.de>
Maintainer: @HRogge 
Compile tested: x86 ath79 ramips
Run tested: x86 ath79 ramips
Description:
oonf-olsrd2: add missing static plugin olsrv2_lan
> oonf-olsrd2: add missing static plugin olsrv2_lan

- bird2/Makefile
Maintainer: @tohojo  (find it by checking history of the package Makefile)
Description:
> bird2: bump to version 2.0.12

- .github/workflows/formal.yml
- .github/workflows/multi-arch-test-build.yml
Update checkout and upload-artifact action to v3 to mute nodejs deprecation warning.
Backported from https://github.com/openwrt/packages/pull/19705
> ci: update github actions to v3

- bird1-openwrt/Makefile
This commit replaces the deprecated licensing text with an SPDX license identifier, and removes tab indentations in the `conffiles` sections. These issues were kindly reported by @BKPepe at #928 after merging, so they're being fixed here.
> bird1-openwrt: fix Makefile issues

- oonf-olsrd2/Makefile
- oonf-olsrd2/patches/100-enable-lan-import-plugin.patch
Development of OONF is very slow. The master branch is completely out of date and new releases haven't been tagged since 2018. According to this PR https://github.com/OLSR/OONF/pull/49#issuecomment-1229195523 the authors will probably just abandon the current master branch and replace it by the develop branch. During my testing, the current development branch is more stable than the latest tagged version on current OpenWrt versions.
Maintainer: me
Compile tested: Ubiquiti ER-X-SFP, MT7621 with both OpenWrt 22.03 and latest master.
Run tested: Ubiquiti ER-X-SFP, MT7621 with both OpenWrt 22.03 and latest master. 22.03 running stable since multiple weeks on my roof.
> oonf-olsrd2: update to current develop branch - fixes routing#899

- batman-adv/patches/0005-fix-batadv_is_cfg80211_netdev.patch
Maintainer: @simonwunderlich @ecsv
Compile tested: bcm2711
Run tested: bcm2711, start batman, enjoy a warning-free dmesg
Description:
Because batman-adv is built under backports, not a clean linux tree, the CONFIG_CFG80211 does not exist. The evaluation of IS_ENABLED() in batadv_is_cfg80211_netdev() will be false, causing the funtion to always return false.
This means that the wifi_flags of an interface don't get set, causing batadv_is_wifi_hardif() to always return false. As a result, batadv_v_elp_get_throughput() never tries to get the station info from cfg80211, resulting in the following warning:
batman_adv: bat0: WiFi driver or ethtool info does not provide
information about link speeds on interface phy1-mesh0,
therefore defaulting to hardcoded throughput values of 1.0 Mbps.
So …
> batman-adv: fix compilation bug in batadv_is_cfg80211_netdev()

- alfred/Makefile
- batctl/Makefile
- prince/Makefile
This refactors packages to use the new PKG_BUILD_FLAGS feature added to the main repo.
> treewide: refactor to use PKG_BUILD_FLAGS

- bird2/Makefile
Signed-off-by: Bradford Zhang <zyc@zyc.name>
(cherry picked from commit bcc6139ad8030b26e71e9217c6c1d5316f941970)
Maintainer: @tohojo  (find it by checking history of the package Makefile)
Description:
> bird2: bump to version 2.13

- cjdns/patches/040-gyp-python_310.patch
Maintainer: me
Compile tested: bpi
Run tested: no run 
Description: fixes dep issue for hosts building with python 3.10
> cjdns: patch of gyp imports support python3.10

- oonf-init-scripts/files/oonf_init.sh
- oonf-olsrd2/Makefile
- oonf-olsrd2/files/olsrd2.init
Maintainer: @stargieg  / @XDjackieXD (find it by checking history of the package Makefile)
Compile tested: mips24k, master
Run tested: mips24k, ran service status / running commands
Description:
Adds the "running" and "status" commands.
Since olsr2 doesn't use procd, we need to add them by hand.
> oonf-olsrd2: add support to check if service is running

- luci-app-olsrd2/Makefile
- luci-app-olsrd2/htdocs/luci-static/resources/view/olsrd2/overview.js
Maintainer: patrick@lunatiki.de @stargieg
Compile tested: mips_24kc, arm_cortex-a9_vfpv3-d16, i386_pentium4, x86_64, i386_pentium-mmx, mipsel_24kc
Run tested: Firefox, Safari
Description: add html table for all LAN prefixes instead of a list with the one/first prefix
Signed-off-by: Patrick Grimm <patrick@lunatiki.de>
> luci-app-olsrd2: add html table for all LAN prefixes

- opennds/Makefile
opennds: Release v10.1.0
Description:
This version is a major upgrade including full migration to nftables
and native uci configuration support even for generic Linux distributions.
It also includes a significant refactoring of inbuilt memory management,
improving long term reliability, fixing several memory leaks, buffer overflows and several edge case crashes.
* Add - support for included custom binauth script [bluewavenet]
* Add - emit a useful stderr message if auth_restore fails [bluewavenet]
* Add - procd respawn threshold, respawn timeout and respawn retry parameters [bluewavenet]
* Add - user …
> opennds: Release v10.1.0

- bird2/Makefile
Maintainer: @tohojo  (find it by checking history of the package Makefile)
Description:
> bird2: bump to version 2.13.1

- opennds/Makefile
opennds (10.1.0)
This version is a major upgrade including full migration to nftables
and native uci configuration support even for generic Linux distributions.
It also includes a significant refactoring of inbuilt memory management,
improving long term reliability, fixing several memory leaks, buffer overflows and several edge case crashes.
* Add - support for included custom binauth script [bluewavenet]
* Add - emit a useful stderr message if auth_restore fails [bluewavenet]
* Add - procd respawn threshold, respawn timeout and respawn retry parameters [bluewavenet]
* Add - user friendly commandline …
> [22.03] opennds: Release v10.1.0

- opennds/Makefile
opennds (10.1.0)
This version is a major upgrade including full migration to nftables
and native uci configuration support even for generic Linux distributions.
It also includes a significant refactoring of inbuilt memory management,
improving long term reliability, fixing several memory leaks, buffer overflows and several edge case crashes.
* Add - support for included custom binauth script [bluewavenet]
* Add - emit a useful stderr message if auth_restore fails [bluewavenet]
* Add - procd respawn threshold, respawn timeout and respawn retry parameters [bluewavenet]
* Add - user friendly commandline …
> [23.05] opennds: Release v10.1.0

- opennds/Makefile
Description:
opennds (10.1.1)
* This version contains some minor bug fixes and documentation updates
* Fix - send only contents of buffer, not entire buffer when serving page511 [bluewavenet]
* Fix - Set fas_remotefqdn to gw_fqdn when overriding FAS settings [bluewavenet]
* Fix - use absolute path for css and images in ThemeSpec [bluewavenet]
* Fix - revert to old option names without underscores [bluewavenet]
* Fix - FAS URL when fas_remotefqdn is not set [bluewavenet]
> opennds: Release v10.1.1

- babeld/Makefile
- babeld/patches/100-local-make-local_kind-function-accessible.patch
- babeld/patches/600-add-ubus.patch
- babeld/src/ubus.c
Announcement:
https://alioth-lists.debian.net/pipermail/babel-users/2023-July/004100.html
Babeld removed diversity routing [0], so we need to adjust ubus bindings. Further. we need to add a patch that makes local_kind accessible again: "100-local-make-local_kind-function-accessible.patch"
Refresh patches:
- 600-add-ubus.patch
[0] - https://github.com/jech/babeld/commit/a0816083356e5d33fb71e0e30d92aa3bf335d7ea
Maintainer: me
Compile tested: mt7621, mt7622
Run tested: mt7622
> babeld: update to 1.13

- opennds/Makefile
Description:
opennds (10.1.1)
* This version contains some minor bug fixes and documentation updates
* Fix - send only contents of buffer, not entire buffer when serving page511 [bluewavenet]
* Fix - Set fas_remotefqdn to gw_fqdn when overriding FAS settings [bluewavenet]
* Fix - use absolute path for css and images in ThemeSpec [bluewavenet]
* Fix - revert to old option names without underscores [bluewavenet]
* Fix - FAS URL when fas_remotefqdn is not set [bluewavenet]
(cherry picked from commit 26f5f0f812c73a3d26f9643fbd3da7f56f5e9a8a)
> [23.05] opennds: Release v10.1.1

- nodogsplash/Makefile
Maintainer: me
Compile tested: Nexx wt3020 ramips/mt7620, OpenWrt master
Run tested: same as compile target
Description:
Tested Internet access via accept button on the splash site.
> nodogsplash: update to 5.0.1

- nodogsplash/Makefile
Cherry picked from https://github.com/openwrt/routing/pull/997 since this includes an important security fix to protect against path tracersal attacks.
> [23.05] nodogsplash: update to 5.0.1

- nodogsplash/Makefile
OpenNDS lists nodogsplash a conflict as well.
This causes a circular reference that is not allowed.
> nodogsplash: remove opennds from conflicts

- opennds/Makefile
Description:
opennds (10.1.2)
Security Advisory - This version contains fixes for multiple potential security vulnerabilities
Credit - Stanislav Dashevskyi - standash.github.io [standash]
It also contains some minor bug fixes
* Fix - Generate unique sha256 faskey if not set in config - CVE-2023-38324 [bluewavenet]
* Fix - NULL pointer dereference if user_agent is NULL - CVE-2023-38320, CVE-2023-38322 [bluewavenet]
* Fix - NULL pointer dereference if authdir is called with an incomplete or missing query string - CVE-2023-38313, CVE-2023-38314, CVE-2023-38315 [bluewavenet]
* Fix - remove deprecated and …
> opennds: Release v10.1.2

- opennds/Makefile
Description:
opennds (10.1.2)
Security Advisory. This version contains fixes for multiple potential security vulnerabilities
Credit - Stanislav Dashevskyi - standash.github.io [standash]
It also contains some minor bug fixes
* Fix - Generate unique sha256 faskey if not set in config - CVE-2023-38324 [bluewavenet]
* Fix - NULL pointer dereference if user_agent is NULL - CVE-2023-38320, CVE-2023-38322 [bluewavenet]
* Fix - NULL pointer dereference if authdir is called with an incomplete or missing query string - CVE-2023-38313, CVE-2023-38314, CVE-2023-38315 [bluewavenet]
* Fix - remove deprecated and …
> [22.03] opennds: Release v10.1.2

- mesh11sd/Makefile
Description:
mesh11sd (2.0.0)
This release contains new functionality.
Autonomous portal mode is introduced. This simplifies the rollout of meshnodes allowing a common configuration to be used on all nodes. Remote administration is introduced, allowing files to be copied and terminal sessions to be opened on established meshnodes, identifying remote nodes by mac address.
* Add - Update config file [bluewavenet]
* Add - implementation of remote copy [bluewavenet]
* Add - implementation of remote connect [bluewavenet]
* Add - Autonomous portal mode [bluewavenet]
-- Rob White dot@blue-wave.net Mon, 31 Jul 2023 16:59:52 +0000
Signed-off-by: Rob …
> mesh11sd: Release v2.0.0

- nodogsplash/Makefile
Maintainer: me
Description: This should alos go to 22.03 since it fixes CVE-2023-39120
> [22.03] nodogsplash: update to 5.0.1

- mesh11sd/Makefile
Description:
mesh11sd (2.0.0)
This release contains new functionality.
Autonomous portal mode is introduced. This simplifies the rollout of meshnodes allowing a common configuration to be used on all nodes. Remote administration is introduced, allowing files to be copied and terminal sessions to be opened on established meshnodes, identifying remote nodes by mac address.
* Add - Update config file [bluewavenet]
* Add - implementation of remote copy [bluewavenet]
* Add - implementation of remote connect [bluewavenet]
* Add - Autonomous portal mode [bluewavenet]
-- Rob White dot@blue-wave.net Mon, 31 Jul 2023 16:59:52 +0000
Signed-off-by: Rob …
> [23.05] mesh11sd: update to version 2.0.0

- mesh11sd/Makefile
Description:
mesh11sd (2.0.0)
This release contains new functionality.
Autonomous portal mode is introduced. This simplifies the rollout of meshnodes allowing a common configuration to be used on all nodes. Remote administration is introduced, allowing files to be copied and terminal sessions to be opened on established meshnodes, identifying remote nodes by mac address.
* Add - Update config file [bluewavenet]
* Add - implementation of remote copy [bluewavenet]
* Add - implementation of remote connect [bluewavenet]
* Add - Autonomous portal mode [bluewavenet]
-- Rob White dot@blue-wave.net Mon, 31 Jul 2023 16:59:52 +0000
Signed-off-by: Rob …
> [22.03] mesh11sd: update to version 2.0.0

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
batman-adv
==========
* support latest kernels (4.14 - 6.5)
- avoid potential invalid memory access when processing ELP/OGM2 packets
- drop pending DAT worker when interface shuts down
- inform network stack about automatically adjusted MTUs
- keep user defined MTU limit when MTU is recalculated
- fix packet memory leak when sending OGM2 via inactive interfaces
- fix TT memory leak for roamed back clients
alfred
======
* receive data with valid source on unix sock without active interface
> batman-adv: update packages to version 2023.2

- batman-adv/Makefile
- batman-adv/patches/0003-batman-adv-Broken-sync-while-rescheduling-delayed-wo.patch
- batman-adv/patches/0004-batman-adv-compat-Use-native-kstrtox.h-for-5.10.185.patch
- batman-adv/patches/0005-batman-adv-Do-not-get-eth-header-before-batadv_check.patch
- batman-adv/patches/0006-batman-adv-Trigger-events-for-auto-adjusted-MTU.patch
- batman-adv/patches/0007-batman-adv-Don-t-increase-MTU-when-set-by-user.patch
- batman-adv/patches/0008-batman-adv-Fix-TT-global-entry-leak-when-client-roam.patch
- batman-adv/patches/0009-batman-adv-Fix-batadv_v_ogm_aggr_send-memory-leak.patch
Compile tested: ramips mt7621
Run tested: ramips mt7621 TP-Link EAP615-Wall v1
batman-adv
==========
* Broken sync while rescheduling delayed work
* compat: Use native kstrtox.h for 5.10.185
* Do not get eth header before batadv_check_management_packet
* Trigger events for auto adjusted MTU
* Don't increase MTU when set by user
* Fix TT global entry leak when client roamed back
* Fix batadv_v_ogm_aggr_send memory leak
> openwrt-23.05: batman-adv: Merge bugfixes from 2023.2

- batman-adv/patches/0013-batman-adv-Broken-sync-while-rescheduling-delayed-wo.patch
- batman-adv/patches/0014-batman-adv-compat-Use-native-kstrtox.h-for-5.10.185.patch
- batman-adv/patches/0015-batman-adv-Do-not-get-eth-header-before-batadv_check.patch
- batman-adv/patches/0016-batman-adv-Trigger-events-for-auto-adjusted-MTU.patch
- batman-adv/patches/0017-batman-adv-Don-t-increase-MTU-when-set-by-user.patch
- batman-adv/patches/0018-batman-adv-Fix-TT-global-entry-leak-when-client-roam.patch
- batman-adv/patches/0019-batman-adv-Fix-batadv_v_ogm_aggr_send-memory-leak.patch
Compile tested: ramips mt7621
Run tested: ramips mt7621 TP-Link EAP615-Wall v1
batman-adv
==========
* Broken sync while rescheduling delayed work
* compat: Use native kstrtox.h for 5.10.185
* Do not get eth header before batadv_check_management_packet
* Trigger events for auto adjusted MTU
* Don't increase MTU when set by user
* Fix TT global entry leak when client roamed back
* Fix batadv_v_ogm_aggr_send memory leak
> openwrt-22.03: batman-adv: Merge bugfixes from 2023.2

- batman-adv/patches/0020-batman-adv-Fix-batadv_v_ogm_aggr_send-memory-leak.patch
The automatic recalculation of the maximum allowed MTU is usually triggered by code sections which are already rtnl lock protected by callers outside of batman-adv. But when the fragmentation setting is changed via batman-adv's own batadv genl family, then the rtnl lock is not yet taken.
But dev_set_mtu requires that the caller holds the rtnl lock because it uses netdevice notifiers. And this code will then fail the check for this lock:
RTNL: assertion failed at net/core/dev.c (1953)
Fixes: e7ee4c55ded3 ("batman-adv: update to version 2023.2")
> openwrt-22.03: batman-adv: Fix lock assert after fragmentation change

- batman-adv/Makefile
- batman-adv/patches/0003-batman-adv-Hold-rtnl-lock-during-MTU-update-via-netl.patch
The automatic recalculation of the maximum allowed MTU is usually triggered by code sections which are already rtnl lock protected by callers outside of batman-adv. But when the fragmentation setting is changed via batman-adv's own batadv genl family, then the rtnl lock is not yet taken.
But dev_set_mtu requires that the caller holds the rtnl lock because it uses netdevice notifiers. And this code will then fail the check for this lock:
RTNL: assertion failed at net/core/dev.c (1953)
Fixes: e7ee4c55ded3 ("batman-adv: update to version 2023.2")
> batman-adv: Fix lock assert after fragmentation change

- batman-adv/Makefile
- batman-adv/patches/0010-batman-adv-Hold-rtnl-lock-during-MTU-update-via-netl.patch
The automatic recalculation of the maximum allowed MTU is usually triggered by code sections which are already rtnl lock protected by callers outside of batman-adv. But when the fragmentation setting is changed via batman-adv's own batadv genl family, then the rtnl lock is not yet taken.
But dev_set_mtu requires that the caller holds the rtnl lock because it uses netdevice notifiers. And this code will then fail the check for this lock:
RTNL: assertion failed at net/core/dev.c (1953)
Fixes: c738e4751e82 ("batman-adv: Merge bugfixes from 2023.2")
> openwrt-23.05: batman-adv: Fix lock assert after fragmentation change

- opennds/Makefile
Description:
opennds (10.1.3)
Security Advisory. This version contains fixes for multiple potential security vulnerabilities Credit - Stanislav Dashevskyi - standash.github.io [standash] It also contains some minor bug fixes
* Fix - Buffer overflow causing segfault - CVE-2023-41101 [bluewavenet]
* Fix - Memory leaks due to passing allocated buffer into safe_asprintf() - CVE-2023-41102 [bluewavenet]
* Fix - Remove deprecated preauth option [bluewavenet]
* Fix - missing free in show_preauth_page if MHD does not respond [bluewavenet]
* Fix - more safe_asprintf memory leaks [bluewavenet]
* Fix - missing free …
> opennds: update to version 10.1.3

- opennds/Makefile
Description:
opennds (10.1.3)
Security Advisory. This version contains fixes for multiple potential security vulnerabilities
Credit - Stanislav Dashevskyi - standash.github.io [standash]
It also contains some minor bug fixes
* Fix - Buffer overflow causing segfault - CVE-2023-41101 [bluewavenet]
* Fix - Memory leaks due to passing allocated buffer into safe_asprintf() - CVE-2023-41102 [bluewavenet]
* Fix - Remove deprecated preauth option [bluewavenet]
* Fix - missing free in show_preauth_page if MHD does not respond [bluewavenet]
* Fix - more safe_asprintf memory leaks [bluewavenet]
* Fix - missing free …
> [23.05] opennds: update to version 10.1.3

- opennds/Makefile
Description:
opennds (10.1.3)
Security Advisory. This version contains fixes for multiple potential security vulnerabilities
Credit - Stanislav Dashevskyi - standash.github.io [standash]
It also contains some minor bug fixes
* Fix - Buffer overflow causing segfault - CVE-2023-41101 [bluewavenet]
* Fix - Memory leaks due to passing allocated buffer into safe_asprintf() - CVE-2023-41102 [bluewavenet]
* Fix - Remove deprecated preauth option [bluewavenet]
* Fix - missing free in show_preauth_page if MHD does not respond [bluewavenet]
* Fix - more safe_asprintf memory leaks [bluewavenet]
* Fix - missing free …
> [22.03] opennds: update to version 10.1.3

- nodogsplash/Makefile
- nodogsplash/files/etc/config/nodogsplash
- nodogsplash/files/etc/init.d/nodogsplash
- nodogsplash/files/etc/uci-defaults/40_nodogsplash
- nodogsplash/files/usr/lib/nodogsplash/restart.sh
Fix a buffer overflow in case the query string is too long.
Maintainer: me
Compile tested: Nexx wt3020, ramips/mt7620
Run tested: save as compiled; tested internet blocked and unblocked after splash site click
> nodogsplash: update to version 5.0.2

- bird2/Makefile
Compile tested: (x86-64, OpenWrt 23.05.0-rc4)
Run tested: (x86-64, OpenWrt 23.05.0-rc4, tests done)
Description:
> bird2: bump to version 2.14

- nodogsplash/Makefile
Maintainer: me
Compile tested: pipeline
> nodogsplash: explicit file copy

- nodogsplash/Makefile
- nodogsplash/files/etc/config/nodogsplash
- nodogsplash/files/etc/init.d/nodogsplash
- nodogsplash/files/etc/uci-defaults/40_nodogsplash
- nodogsplash/files/usr/lib/nodogsplash/restart.sh
Fix a buffer overflow in case the query string is too long.
(cherry picked from commit fe1c67fb3d83089210d5b45bc35eb7d7393aeb1f)
Maintainer: me
> [openwrt-23-05] nodogsplash: update to version 5.0.2

- nodogsplash/Makefile
- nodogsplash/files/etc/config/nodogsplash
- nodogsplash/files/etc/init.d/nodogsplash
- nodogsplash/files/etc/uci-defaults/40_nodogsplash
- nodogsplash/files/usr/lib/nodogsplash/restart.sh
Fix a buffer overflow in case the query string is too long.
(cherry picked from commit fe1c67fb3d83089210d5b45bc35eb7d7393aeb1f)
Maintainer: me
> [openwrt-22.03] nodogsplash: update to version 5.0.2

- nodogsplash/Makefile
- nodogsplash/files/etc/config/nodogsplash
- nodogsplash/files/etc/init.d/nodogsplash
- nodogsplash/files/etc/uci-defaults/40_nodogsplash
- nodogsplash/files/usr/lib/nodogsplash/restart.sh
Fix a buffer overflow in case the query string is too long.
(cherry picked from commit fe1c67fb3d83089210d5b45bc35eb7d7393aeb1f)
Maintainer: me
> [openwrt-21.02] nodogsplash: update to version 5.0.2

- cjdns/Makefile
Maintainer: @wfleurant
Compile tested: rpi4 aarch64/7xx/trunk
Run tested: builds
Description: builds
> cjdns: always build without ccache prefix (#1030)

- opennds/Makefile
Description:
opennds (10.2.0) - This version is a minor upgrade that introduces some significant additional functionality.
In addition it includes numerous enhancements bug fixes and cosmetic fixes.
Additional functionality includes:
* Pre-emptive Client Lists
* Autonomous Block Lists
* Internet hosted https FAS support for resource limited routers
* Fair Usage Policy
https://github.com/openNDS/openNDS/releases/tag/v10.2.0
> opennds: update to version 10.2.0

- opennds/Makefile
Description:
opennds (10.2.0) - This version is a minor upgrade that introduces some significant additional functionality. In addition it includes numerous enhancements bug fixes and cosmetic fixes.
Additional functionality includes:
* Pre-emptive Client Lists
* Autonomous Block Lists
* Internet hosted https FAS support for resource limited routers
* Fair Usage Policy
https://github.com/openNDS/openNDS/releases/tag/v10.2.0
(cherry picked from commit a5ec54aee3df6aa400e454ef0468127dcd0c6b25)
> [23.05] opennds: update to version 10.2.0

- batman-adv/Makefile
- batman-adv/src/compat-hacks.h
Maintainer:  @simonwunderlich 
Compile tested: ramips / mipsel_24kc (mt76x8)
Run tested: -
Description:
The newest Linux stable kernel releases:
* v5.10.205
* v5.15.144
* v6.1.69
received a backported version of commit 1f5020acb33f ("net: vlan: introduce skb_vlan_eth_hdr()"). batman-adv must therefore not provide this function any longer for these kernel versions.
Closes: #1036
> openwrt-23.05: batman-adv: compat: Fix skb_vlan_eth_hdr conflict in stable kernels

- batman-adv/Makefile
- batman-adv/src/compat-hacks.h
Maintainer:  @simonwunderlich 
Compile tested: ramips / mipsel_24kc (mt76x8)
Run tested: -
Description:
The newest Linux stable kernel releases:
* v5.10.205
* v5.15.144
* v6.1.69
received a backported version of commit 1f5020acb33f ("net: vlan: introduce skb_vlan_eth_hdr()"). batman-adv must therefore not provide this function any longer for these kernel versions.
Closes: #1036
> batman-adv: compat: Fix skb_vlan_eth_hdr conflict in stable kernels

- batctl/Makefile
- batctl/patches/0001-batctl-tcpdump-Fix-missing-sanity-check-for-batman-a.patch
- batctl/patches/0002-batctl-tcpdump-Add-missing-throughput-header-length-.patch
- batctl/patches/0003-batctl-tcpdump-Fix-IPv4-header-length-check.patch
- batctl/patches/0004-batctl-tcpdump-Add-missing-ICMPv6-Neighbor-Advert-le.patch
- batctl/patches/0005-batctl-tcpdump-Add-missing-ICMPv6-Neighbor-Solicit-l.patch
- batctl/patches/0006-batctl-tcpdump-Fix-ICMPv4-inner-IPv4-header-length-c.patch
Description:
* tcpdump: Fix missing sanity check for batman-adv header
* tcpdump: Add missing throughput header length check
* tcpdump: Fix IPv4 header length check
* tcpdump: Add missing ICMPv6 Neighbor Advert length check
* tcpdump: Add missing ICMPv6 Neighbor Solicit length check
* tcpdump: Fix ICMPv4 inner IPv4 header length check
> openwrt-23.05: batctl: Merge bugfixes from 2024.0

- batman-adv/Makefile
- batman-adv/files/lib/netifd/proto/batadv_vlan.sh
Compile tested: ath79, GL.iNet GL-AR750
Run tested: ath79, GL.iNet GL-AR750
Description:
The batadv_vlan proto doesn't need to do anything when it gets teared down. But the scripts are still trying to call the teardown function of this proto. This results in warnings like:
daemon.notice netifd: batmesh1 (18940): ./batadv_vlan.sh: eval: line 37: proto_batadv_vlan_teardown: not found
Just providing a stub function avoids this log spam.
Fixes: #1044
Reported-by: Rani Hod <rani.hod@gmail.com>
Fixes: f5205d7d2434 ("batman-adv: upgrade package to latest release 2014.2.0")
> batman-adv: Provide teardown hook for batadv_vlan proto

- batman-adv/Makefile
- batman-adv/files/lib/netifd/proto/batadv_vlan.sh
Compile tested: ath79, GL.iNet GL-AR750
Run tested: ath79, GL.iNet GL-AR750
Description:
The batadv_vlan proto doesn't need to do anything when it gets teared down. But the scripts are still trying to call the teardown function of this proto. This results in warnings like:
daemon.notice netifd: batmesh1 (18940): ./batadv_vlan.sh: eval: line 37: proto_batadv_vlan_teardown: not found
Just providing a stub function avoids this log spam.
Fixes: #1044
Reported-by: Rani Hod <rani.hod@gmail.com>
Fixes: f5205d7d2434 ("batman-adv: upgrade package to latest release 2014.2.0")
> openwrt-23.05: batman-adv: Provide teardown hook for batadv_vlan proto

- batman-adv/Makefile
- batman-adv/files/lib/netifd/proto/batadv_vlan.sh
Compile tested: ath79, GL.iNet GL-AR750
Run tested: ath79, GL.iNet GL-AR750
Description:
The batadv_vlan proto doesn't need to do anything when it gets teared down. But the scripts are still trying to call the teardown function of this proto. This results in warnings like:
daemon.notice netifd: batmesh1 (18940): ./batadv_vlan.sh: eval: line 37: proto_batadv_vlan_teardown: not found
Just providing a stub function avoids this log spam.
Fixes: #1044
Reported-by: Rani Hod <rani.hod@gmail.com>
Fixes: f5205d7d2434 ("batman-adv: upgrade package to latest release 2014.2.0")
> openwrt-22.03: batman-adv: Provide teardown hook for batadv_vlan proto

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, mips_24kc, aarch64_cortex-a53, x86-64
Description:
mesh11sd (3.1.0)
This release contains new functionality and numerous fixes.
New functionality includes support of non-mesh segments of backhaul
with blocking of bridge loops and spanning tree priority settable in the configuration
https://github.com/openNDS/mesh11sd/releases/tag/v3.1.0
> mesh11sd: update to version 3.1.0

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, mips_24kc, aarch64_cortex-a53, x86-64
Description:
mesh11sd (3.1.0)
This release contains new functionality and numerous fixes.
New functionality includes support of non-mesh segments of backhaul
with blocking of bridge loops and spanning tree priority settable in the configuration
https://github.com/openNDS/mesh11sd/releases/tag/v3.1.0
(cherry picked from commit 4af9b69e1ba22a7406e20cdfb4982962e631fce4)
> [23.05] mesh11sd: update to version 3.1.0

- batman-adv/Makefile
- batman-adv/patches/0011-batman-adv-Avoid-infinite-loop-trying-to-resize-loca.patch
If the MTU of one of an attached interface becomes too small to transmit the local translation table then it must be resized to fit inside all fragments (when enabled) or a single packet.
But if the MTU becomes too low to transmit even the header + the VLAN specific part then the resizing of the local TT will never succeed. This can for example happen when the usable space is 110 bytes and 11 VLANs are on top of batman-adv. In this case, at least 116 byte would be needed. There will just be an endless spam of
batman_adv: batadv0: Forced to purge local tt entries to fit new maximum fragment MTU (110)
in the log but the function will never finish. Problem here is that the timeout will be halved all the time and will …
> openwrt-23.05: batman-adv: Avoid infinite loop trying to resize local TT

- mesh11sd/Makefile
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, mips_24kc, aarch64_cortex-a53, x86-64
Description:
mesh11sd (3.1.1)
This release contains several bug fixes.
These fixes include improved ndp scan and more reliable peer node identification.
https://github.com/openNDS/mesh11sd/releases/tag/v3.1.1
> mesh11sd: update to version 3.1.1

- cjdns/Makefile
Maintainer: @wfleurant 
Compile tested: mipsel_24kc
Run tested: -
Description
With a switch to APK, the version schema becomes a hard requirement and may not contain arbitrary letters. Remove the `v` and attach it only while downloading/building.
> cjdns: switch version to be APK compatible

- bird2/Makefile
> bird2: bump to version 2.15.1

- mesh11sd/Makefile
Description:
mesh11sd (4.0.1)
This minor bugfix release follows on from the previous major release which introduced
new functionality that includes autonomous path stabilisation and the support of mesh leechnodes.
https://github.com/openNDS/mesh11sd/releases/tag/v4.0.1
(cherry picked from commit 56f7ad193382200764c54ac3c5f55abe72fa7f4e)
> [23.05] mesh11sd: update to version 4.0.1

- bird2/test.sh
Compile tested: x86_64 generic
Run tested: x86_64 generic test done
Description: add test.sh for bird2
> bird2: add test.sh for bird

- opennds/Makefile
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, aarch64_cortex-a53, x86-64
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, mips_24kc, aarch64_cortex-a53, x86-64 ;
Description:
opennds (10.3.0) - This version is a minor upgrade that introduces some significant additional functionality. In addition it includes numerous enhancements bug fixes and cosmetic fixes.
Additional functionality includes:
1. Support for integration of Mesh11sd meshnodes
2. Download protocol debugging
3. Resolving of fqdn ip addresses on CDN systems with multiple ip addresses
4. Support for specifying alternate dhcp leases file location
https://github.com/openNDS/openNDS/releases/tag/v10.3.0
> opennds: update to version 10.3.0

- opennds/Makefile
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, aarch64_cortex-a53, x86-64
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, mips_24kc, aarch64_cortex-a53, x86-64 ;
Description:
opennds (10.3.0) - This version is a minor upgrade that introduces some significant additional functionality. In addition it includes numerous enhancements bug fixes and cosmetic fixes.
Additional functionality includes:
1. Support for integration of Mesh11sd meshnodes
2. Download protocol debugging
3. Resolving of fqdn ip addresses on CDN systems with multiple ip addresses
4. Support for specifying alternate dhcp leases file location
https://github.com/openNDS/openNDS/releases/tag/v10.3.0
Signed-off-by: Rob …
> [23.05] opennds: update to version 10.3.0

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/patches/0003-Revert-batman-adv-Switch-to-linux-sprintf.h.patch
- batman-adv/patches/0004-Revert-batman-adv-Switch-to-linux-array_size.h.patch
Description:
batman-adv
==========
* support latest kernels (4.19 - 6.10)
> batman-adv: update packages to version 2024.2

- mesh11sd/Makefile
Description: mesh11sd (4.1.0)
This release adds new functionality that includes support for:
* Opportunistic Wireless Encryption (OWE) on mesh gates.
* Customer[Client] Premises Equipment mode (CPE) on mesh gates.
https://github.com/openNDS/mesh11sd/releases/tag/v4.1.0
> mesh11sd: update to version 4.1.0

- mesh11sd/Makefile
Description: mesh11sd (4.1.0)
This release adds new functionality that includes support for:
* Opportunistic Wireless Encryption (OWE) on mesh gates.
* Customer[Client] Premises Equipment mode (CPE) on mesh gates.
https://github.com/openNDS/mesh11sd/releases/tag/v4.1.0
(cherry picked from commit 3a773abd3f00e52059d826bcacc74ec09fba8bbb)
> [23.05] mesh11sd: update to version 4.1.0

- mesh11sd/Makefile
Description: mesh11sd (4.1.1)
This release provides a critical bug fix.
In non-cpe peer mode, if the portal node dhcp6 server fails to respond or cannot be reached, multiple instances of odhcp6c are created, resulting in an eventual oom condition.
https://github.com/openNDS/mesh11sd/releases/tag/v4.1.1
> mesh11sd: update to version 4.1.1

- mesh11sd/Makefile
Description: mesh11sd (4.1.1)
This release provides a critical bug fix.
In non-cpe peer mode, if the portal node dhcp6 server fails to respond or cannot be reached, multiple instances of odhcp6c are created, resulting in an eventual oom condition.
https://github.com/openNDS/mesh11sd/releases/tag/v4.1.1
(cherry picked from commit 31e66c083940775508b29b9ec2776db4be3f3633)
> [23.05] mesh11sd: update to version 4.1.1

- babeld/Makefile
- babeld/src/ubus.c
Maintainer: gabriel@kerneis.info openwrt-pkg@bitsofnetworks.org vincent@systemli.org
Compile tested: ar71xx, ath79, mvebu, x86_64
Run tested: ca. 30 Freifunk nodes
Description:
- use an array for routing lists
- use underscore in key name for libubox/jshn.sh compat
Fix: openwrt/luci/issues/6342
Fix: openwrt/routing/issues/966
Signed-off-by: Patrick Grimm <patrick@lunatiki.de>
> babeld: use an array for routing lists

- batctl/Makefile
- batctl/patches/0007-batctl-Dynamically-select-header-format-in-netlink_p.patch
- batman-adv/Makefile
- batman-adv/patches/0012-batman-adv-Don-t-accept-TT-entries-for-out-of-spec-V.patch
Description:
batman-adv
==========
* Don't accept TT entries for out-of-spec VIDs
batctl
======
* Dynamically select header format in netlink_print_neighbors
> openwrt-23.05: batman-adv: Import bugfixes from 2024.3 release

- ndppd/Makefile
- ndppd/patches/0001-Version-bump.patch
- ndppd/patches/0002-Fixes-strerror_r-GNU-XSI.patch
- ndppd/patches/0003-fix-poll-header.patch
Maintainer: @kerneis
Compile tested: x86-64, generic, snapshot
Run tested: x86-64, generic, snapshot
Description:
ndppd has tagged commit eb81b8f as 0.2.6.
https://github.com/openwrt/routing/pull/1082
https://github.com/DanielAdolfsson/ndppd/issues/90
https://github.com/DanielAdolfsson/ndppd/releases/tag/0.2.6
> ndppd: update to version 0.2.6

- bird2/Makefile
Import patch from Freifunk to enable -mno-unaligned-access - see upstream bug report:
http://trubka.network.cz/pipermail/bird-users/2024-December/017944.html
Ref: https://github.com/freifunk-berlin/falter-packages/pull/454
> bird2: Prevent unaligned access on ARM

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/patches/0003-Revert-batman-adv-move-asm-unaligned.h-to-linux-unal.patch
- batman-adv/src/compat-hacks.h
Description:
batman-adv
==========
* support latest kernels (5.4 - 6.13)
- prevent transmission of uninitialized memory for TT TVLVs
- avoid stuck, overfull translation table changes list
batctl
======
* drop explicit requirement to run as root
> batman-adv: update packages to version 2024.4

- batman-adv/Makefile
- batman-adv/patches/0013-batman-adv-Do-not-send-uninitialized-TT-changes.patch
- batman-adv/patches/0014-batman-adv-Remove-uninitialized-data-in-full-table-T.patch
- batman-adv/patches/0015-batman-adv-Do-not-let-TT-changes-list-grows-indefini.patch
Description:
* Do not send uninitialized TT changes
* Remove uninitialized data in full table TT response
* Do not let TT changes list grows indefinitely
> openwrt-23.05: batman-adv: Merge bugfixes from 2024.4

- batman-adv/Makefile
- batman-adv/patches/0003-batman-adv-Do-not-send-uninitialized-TT-changes.patch
- batman-adv/patches/0004-batman-adv-Remove-uninitialized-data-in-full-table-T.patch
- batman-adv/patches/0005-batman-adv-Do-not-let-TT-changes-list-grows-indefini.patch
Description:
* Do not send uninitialized TT changes
* Remove uninitialized data in full table TT response
* Do not let TT changes list grows indefinitely
> openwrt-24.10: batman-adv: Merge bugfixes from 2024.4

- bird2/Makefile
Upstream release v2.16. Also change download URL to use https instead of ftp.
> bird2: Bump to v2.16

- bird3/Makefile
- bird3/files/bird.init
- bird3/test.sh
@tohojo Is it fine if I add this package and list both you and me as maintainers?
> bird3: add new bird3 package

- bird3/Makefile
- Fixed crashes in dynamic BGP
- Improved graceful recovery mechanism
- Resolved issues with deterministic MED
- Addressed BFD session reconfiguration problems
- Corrected kernel path merging
- Optimized inefficiencies in feeds and refeeds
- Fixed heap bloating issues
- Corrected the name of the bgp_otc route attribute
Maintainer: me, @tohojo 
Compile tested: filogic
> bird3: update to 3.0.1

- bird2/Makefile
Previously, we used the -mno-unaligned-access flag to instruct GCC to forbid unaligned memory access on arm processors. This was a workaround for alignment issues that caused crashes.
This commit imports a patch from the BIRD mailing list discussion [0] that resolves the alignment issue by modifying the net_addr structure, removing the need for the GCC flag. The patch addresses the alignment problem more efficiently and avoids the performance, code size, and hardware optimization drawbacks of the flag.
[0] - http://trubka.network.cz/pipermail/bird-users/2024-December/017957.html
Compile tested: arm7
Run tested: arm7
> bird2: update to 2.16.1

- bird3/Makefile
- bird3/files/bird.init
- bird3/test.sh
Maintainer: me, @tohojo 
Compile tested: filogic
> [24.10] bird3: add bird3

- bird2/Makefile
The bird package has been updated to include a patch that directly fixes the alignment issue, which previously required the use of the -mno-unaligned-access GCC flag on ARM processors. This patch, originally discussed on the BIRD mailing list [0], modifies the net_addr structure to resolve the alignment problem without needing the workaround.
By incorporating this patch, the alignment issue is addressed more efficiently, eliminating the performance, code size, and hardware optimization drawbacks associated with the GCC flag.
Release Notes:
http://trubka.network.cz/pipermail/bird-users/2025-January/018041.html
[0] - http://trubka.network.cz/pipermail/bird-users/2024-December/017957.html
(cherry picked from commit …
> [24.10] bird2: update to 2.16.1

- batman-adv/Makefile
- batman-adv/patches/0006-batman-adv-fix-panic-during-interface-removal.patch
- batman-adv/patches/0007-batman-adv-Ignore-neighbor-throughput-metrics-in-err.patch
- batman-adv/patches/0008-batman-adv-Drop-unmanaged-ELP-metric-worker.patch
Description:
* force stop of throughput detection workers on interface removal
> openwrt-24.10: batman-adv: Merge bugfixes from 2025.0

- alfred/Makefile
- batctl/Makefile
- batman-adv/Makefile
- batman-adv/patches/0003-Revert-batman-adv-move-asm-unaligned.h-to-linux-unal.patch
Description:
batman-adv
==========
* support latest kernels (5.4 - 6.14)
* handle VLAN 0 as untagged VLAN
* TT changes in OGMs no longer contain redundant TT changes
- fix incorrect offset in OGM handler for translation table TVLV
- force stop of throughput detection workers on interface removal
batctl
======
* subsecond precision support for ping intervals
alfred
======
> batman-adv: update packages to version 2025.0

- mesh11sd/Makefile
Description: mesh11sd (5.0.1)
This is a major release, with additional minor fixes. It introduces significant new functionality,
including point to multipoint vxlan tunnelling
and a Centralised Access Point usage database.
https://github.com/openNDS/mesh11sd/blob/v5.0.1/ChangeLog
> mesh11sd: update to version 5.0.1

- opennds/Makefile
Compile tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, aarch64_cortex-a53, x86-64
Run tested: arm_cortex-a7_neon-vfpv4, mipsel_24kc, mips_24kc, aarch64_cortex-a53, x86-64 ;
On 23.5, 24.10 and master/snapshot.
Description: opennds (10.3.1) - This version is a bugfix update. Most importantly, this release fixes the issue where libmicrohttpd version 1.0.0 or higher prevented the openNDS daemon from starting. Numerous other minor fixes are also included.
https://github.com/openNDS/openNDS/releases/tag/v10.3.1
> opennds: update to version 10.3.1

- mesh11sd/Makefile
Description: mesh11sd (5.0.1)
This is a major release, with additional minor fixes. It introduces significant new functionality,
including point to multipoint vxlan tunnelling
and a Centralised Access Point usage database.
https://github.com/openNDS/mesh11sd/blob/v5.0.1/ChangeLog
(cherry picked from commit 5d1d38a60590488841384214d0403fd93ed8ce22)
> [24.10] mesh11sd: update to version 5.0.1

- batman-adv/Makefile
- batman-adv/patches/0009-batman-adv-Ignore-own-maximum-aggregation-size-durin.patch
Description:
* Ignore own maximum aggregation size during RX
> openwrt-24.10: batman-adv: Merge bugfixes from 2025.1

- batman-adv/Makefile
- batman-adv/patches/0019-batman-adv-Ignore-own-maximum-aggregation-size-durin.patch
Description:
* Ignore own maximum aggregation size during RX
> openwrt-23.05: batman-adv: Merge bugfixes from 2025.1

- mesh11sd/Makefile
Description: mesh11sd (5.1.2)
This is a minor bugfix release.
* Improved reading of the uci config, eliminating some discrepancies.
* Consistently use mesh_phy_index, rather then mesh_phyindex as a config option.
https://github.com/openNDS/mesh11sd/blob/v5.1.2/ChangeLog
> mesh11sd: update to version 5.1.2

- mesh11sd/Makefile
Description: mesh11sd (5.1.3)
This is a minor bugfix release.
It includes:
* Fix when converting from/to local administered mac if the first octet is 0
* Fix and improve detection of portal state changes
* Ensure dhcp is disabled on vtunnel when changing to peer mode
https://github.com/openNDS/mesh11sd/blob/v5.1.3/ChangeLog
> mesh11sd: update to version 5.1.3

- mesh11sd/Makefile
mesh11sd: update to version 5.1.3
Description: mesh11sd (5.1.3)
This is a minor bugfix release.
It includes:
* Fix when converting from/to local administered mac if the first octet is 0
* Fix and improve detection of portal state changes
* Ensure dhcp is disabled on vtunnel when changing to peer mode
https://github.com/openNDS/mesh11sd/blob/v5.1.3/ChangeLog
(cherry picked from commit https://github.com/openwrt/routing/commit/02f8722f875c217669792a42723e61c29271bb1b)
> [24.10] mesh11sd: update to version 5.1.3

- batman-adv/Makefile
- batman-adv/patches/0010-batman-adv-fix-duplicate-MAC-address-check.patch
Description:
* fix duplicate MAC address check
> openwrt-24.10: batman-adv: Merge bugfixes from 2025.2

- bird2/Makefile
Maintainer:
Compile tested: Not needed
Run tested: Not needed
> bird2: Add PKG_CPE_ID

- batctl/Makefile
- batctl/patches/0001-batctl-event-Fix-direct-parsing-on-hardif-for-set_ha.patch
- batctl/patches/0002-batctl-Avoid-memory-leak-in-print_routing_algos.patch
- batman-adv/Makefile
- batman-adv/patches/0011-batman-adv-fix-OOB-read-write-in-network-coding-deco.patch
Compile tested: x86-64
Run tested: x86-64
Description:
batman-adv
==========
* fix OOB read/write in network-coding decode
batctl
======
* fix potential memory leak in print_routing_algos
* fix event parsing of hard interface names
> openwrt-24.10: batman-adv: Merge bugfixes from 2025.3

- batmand/Makefile
- vis/Makefile
Maintainer: @BKPepe
Compile tested: no
Run tested: no
Description:
The extra quotation marks in the PKG_MAINTAINER line of the '.packageinfo'   file does not produce valid JSON when [package-metadata.pl pkgmanifestjson](https://github.com/openwrt/openwrt/blob/main/scripts/package-metadata.pl#L820) is used.
Therefore, the word with the surrounding quotation marks is removed.
> treewide: fix maintainer naming by removing incorrect quotation marks
